### ISSUE TITLE
[桌面端]设计资源Axure组件下载后无法打开

### ISSUE THREAD

**Issue by Asunfly** [Tencent/tdesign#107]
### tdesign 版本

axure rp 9

### 重现链接

https://tdesign.tencent.com/

### 重现步骤

https://tdesign.tencent.com/
下载桌面端=>设计资源=>axure
使用axure rp9 打开，资源无法正常加载

**Comment by Asunfly** [comment]
是因为元件库保存时候开了过多标签页导致导入元件库时候卡死了；重新编辑时候把所有标签页关闭然后再导入就可以了

**Comment by 94dreamer** [comment]
@Asunfly  已经解决了？

**Comment by Asunfly** [comment]
> 

是的
