### ISSUE TITLE
增加选项卡显示当前组件名称

### ISSUE THREAD

**Issue by huangzhongzhong** [Tencent/tdesign#11]
**Is your feature request related to a problem? Please describe.**
希望选项卡出现组件的名称，现在是没有的
![image](https://user-images.githubusercontent.com/46183365/147382233-2a342a1d-e10e-4018-a94f-05fc012d29c8.png)

**Describe the solution you'd like**
像 arco 这样可以再选项卡看到组件名称。
![image](https://user-images.githubusercontent.com/46183365/147382190-6770ad33-6342-475e-88b8-afa609ea5718.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by 94dreamer** [comment]
@HQ-Lin

**Comment by HQ-Lin** [comment]
感谢反馈，近期优化下

**Comment by Wen1kang** [comment]
@HQ-Lin 这个要关注下哦

**Comment by HQ-Lin** [comment]
线上已支持
