### ISSUE TITLE
请问是否有计划支持Blazor?

### ISSUE THREAD

**Issue by CeSun** [Tencent/tdesign#116]
Blazor是一个基于wasm与c#的前端框架，使用C#语言替代JS/TS进行前端开发，代码并不需要转译成JS。

请问官方是否会考虑支持Blazor？

**Comment by chaishi** [comment]
c#，我们看看能不能招到会 c# 的同学开这个头

目前都是前端同学，会这个的比较少

**Comment by CeSun** [comment]
哈哈哈，感谢回答！
(js => ts => c# 陡峭的学习路线 )

**Comment by ElderJames** [comment]
来了 https://github.com/AchievedOwner/TDesignBlazor

**Comment by CeSun** [comment]
> 来了 https://github.com/AchievedOwner/TDesignBlazor

赞，希望官方关注一下 @chaishi
