### ISSUE TITLE
官网页面页头/页脚样式错乱

### ISSUE THREAD

**Issue by ayhyh** [Tencent/tdesign#13]
![image](https://user-images.githubusercontent.com/31920592/147440150-579a8183-1794-4c43-82dc-73de4b87b32a.png)
![image](https://user-images.githubusercontent.com/31920592/147440181-54a4b138-8ae3-46c2-afe8-21d24a4efea4.png)

**Comment by pengYYYYY** [comment]
您好，请问一下你的浏览器环境和操作系统是什么？

**Comment by 94dreamer** [comment]
@HQ-Lin  如上

**Comment by 94dreamer** [comment]
@ayhyh  请提供浏览器版本和操作系统

**Comment by oxygen1999** [comment]
![image](https://user-images.githubusercontent.com/62201108/148186872-8bfac15f-575c-42b9-a387-dd54fa9ad94e.png)

**Comment by oxygen1999** [comment]
这都是些什么呀，烦死人了，侧边栏都关不掉的

**Comment by oxygen1999** [comment]
![image](https://user-images.githubusercontent.com/62201108/148187146-2ba7392c-964c-438e-ba58-45dc2b152d9a.png)
这为啥都是这样，看着好难受

**Comment by oxygen1999** [comment]
> 

 版本94.0.4606.61

**Comment by HQ-Lin** [comment]
> > 
> 
> 版本94.0.4606.61

你好，能否使用无痕模式启动下页面试试看会不会错乱，主要想排查下是否是装了某些插件影响到页面的渲染

**Comment by HQ-Lin** [comment]
> > > 
> > 
> > 
> > 版本94.0.4606.61
> 
> 你好，能否使用无痕模式启动下页面试试看会不会错乱，主要想排查下是否是装了某些插件影响到页面的渲染，或者提供一下控制台是否有报错信息

**Comment by oxygen1999** [comment]
> 

![image](https://user-images.githubusercontent.com/62201108/148511115-621b83e8-8980-4dbb-8dab-eeb781b2ba84.png)
无痕模式下是正常的，不是无痕的话样式就会错乱

**Comment by HQ-Lin** [comment]
控制台没有报错那大概率是插件影响到了，试着将一些浏览器插件禁用看看是否恢复正常

**Comment by oxygen1999** [comment]
> 控制台没有报错那大概率是插件影响到了，试着将一些浏览器插件禁用刷新页面看看是否恢复正常

miniprogram/overview这个接口404有影响吗

**Comment by HQ-Lin** [comment]
> > 控制台没有报错那大概率是插件影响到了，试着将一些浏览器插件禁用刷新页面看看是否恢复正常
> 
> miniprogram/overview这个接口404有影响吗

不会有影响，这个报错我去排查下应该是 cdn 的问题。
但是现在代码找到了，页面还错乱就是渲染的问题

**Comment by HQ-Lin** [comment]
> > 控制台没有报错那大概率是插件影响到了，试着将一些浏览器插件禁用刷新页面看看是否恢复正常
> 
> miniprogram/overview这个接口404有影响吗

可以先把所有浏览器插件禁用一下看看是不是正常的，如果是正常的再一个个打开看看到底是哪个影响了

**Comment by oxygen1999** [comment]
> > > 控制台没有报错那大概率是插件影响到了，试着将一些浏览器插件禁用刷新页面看看是否恢复正常
> > 
> > 
> > miniprogram/overview这个接口404有影响吗
> 
> 可以先把所有浏览器插件禁用一下看看是不是正常的，如果是正常的再一个个打开看看到底是哪个影响了

好的，我这边看一下
