### ISSUE TITLE
[时间、日期时间、日期 选择器]希望增加自定义快捷选项 

### ISSUE THREAD

**Issue by tymagic** [Tencent/tdesign#132]
### 这个功能解决了什么问题
快速输入正确时间

### 你建议的方案是什么？
比如 时间选择器有 三小时 当天等等 用户可以自定义

**Comment by xiaosansiji** [comment]
![image](https://user-images.githubusercontent.com/7600149/173813588-4298df56-7b18-48e1-86ab-6d835e0f050d.png)
![image](https://user-images.githubusercontent.com/7600149/173813660-c080ca2e-a575-4e4b-b058-4b47a99529ef.png)
https://tdesign.tencent.com/react/components/date-picker?tab=demo#%E5%B8%A6%E5%BF%AB%E6%8D%B7%E6%A0%87%E7%AD%BE%E7%9A%84%E6%97%A5%E6%9C%9F%E9%80%89%E6%8B%A9%E5%99%A8

看看这个官网的例子能满足你需求不
