### ISSUE TITLE
组件【dropdown下拉菜单】设计优化

### ISSUE THREAD

**Issue by eugenewoody** [Tencent/tdesign#134]
### 这个功能解决了什么问题

解决开发组件和设计稿样式没对齐的问题。

### 你建议的方案是什么

一、【组件dropdown下拉菜单】codesign地址：
https://codesign.qq.com/s/zm5q0XqpvyZRBb6
访问密码：OZEV
二、【组件dropdown下拉菜单】figma源文件地址：https://www.figma.com/file/KInDIZzoxifaKVQ3n5KB8W/?node-id=24901%3A36226
三、具体修改细节如下（详见图片）：
<img width="1190" alt="dropdown切图1" src="https://user-images.githubusercontent.com/103838357/174531425-5169e20c-e3de-4b79-9f7d-62d96d632433.png">
1.下拉菜单选中态下，缺少主题样式（成功、警告、错误）。
2.含下划线的下拉菜单，下划线间距和下划线样式不对。
3.多层下拉菜单样式不对。
4.下拉菜单间距不对，间距为2。
5.下拉菜单圆角不对，圆角为6。
6.没有显示前置icon的下拉菜单。
7.选中态的蓝色色值不对。
8.下拉菜单的宽度，宜采用建议宽度为160。

**Comment by Isabella327** [comment]
我可以试着弄下吗？

**Comment by YunYouJun** [comment]
@Isabella327 同学，请问你已经着手开发了吗？

如果没有的话，我想认领该任务，预估两天之内完成。

**Comment by Isabella327** [comment]
@YunYouJun 还没有开始，你来认领吧

**Comment by Isabella327** [comment]
@YunYouJun 我想试着做一下，已经开始修样式了，后续有问题可以进一步交流好吗。

**Comment by YunYouJun** [comment]
好的，我先看看别的任务。

**Comment by Isabella327** [comment]
@xiaosansiji 有的有的，这边重构和样式我已经做完，但是卡在了overflow这里，暂时没想到解决方案，其他需要确认的问题 1. 高亮选项是什么颜色？我暂时采用select的颜色 2.高亮和disabled会同时使用吗 3.图标位置的设计稿里面图标距离两边9.15px，7.13%这个我没理解，可以确定下吗 4.

**Comment by xiaosansiji** [comment]
1. 高亮使用 select 选项选中的颜色 token 是对的
2. disable 后选项无法选中，不会同时存在
6.宽度应该还是要 API 控制的，有跟随节点宽度和手动设置能力
其他的需要跟设计师同学聊一下，你可以先把其他的提个 PR 过来哈，扫码加下贡献者群：
![image](https://user-images.githubusercontent.com/7600149/182121195-887a199c-20ea-4bda-a2da-75879c47606b.png)
