### ISSUE TITLE
组件【menu导航菜单】设计优化

### ISSUE THREAD

**Issue by eugenewoody** [Tencent/tdesign#141]
### 这个功能解决了什么问题

解决【组件menu】开发样式和设计样式没有对齐的问题。（备注：本次修改建议在dropdown修改完之后进行）

### 你建议的方案是什么

一、【组件menu导航菜单】codesign地址：
https://codesign.qq.com/s/ALwE9VKLvA0X1Dp/QmlyZwrK5oO0WRA/inspect
访问密码：CUOA
二、【组件menu导航菜单】figma源文件地址：
https://www.figma.com/file/KInDIZzoxifaKVQ3n5KB8W/TDesign-for-web?node-id=35282%3A70952
三、具体修改细节如下（详见图片）：
<img width="2264" alt="Menu的截图" src="https://user-images.githubusercontent.com/103838357/176624201-d7a0a9fe-573d-41ed-96c8-cec5106742a3.png">
1.顶部双层导航，二级页面导航为【白色】，颜色不与一级导航同步
2.导航选中态颜色不对
3.导航logo不是最新版本
4.黑色导航，是【黑色主题】，不是暗黑模式！
5.导航与下拉菜单的间距为【0】，且导航菜单内的下拉菜单样式，与【dropdown下拉菜单】组件样式对齐（在这里不一一赘述）
6. 顶部导航的自定义内容区域，建议使用【button】的样式进行展示
7.间距不对
   7.1 单层导航的高是【56】，不是64
   7.2 侧边导航头部和底部的高是【56】，不是64
   7.3 单层导航按钮的高度是【32】，不是40
   7.4 导航菜单的间距为【8】，不是4
8.导航下拉菜单【箭头方向】不对，箭头应该向右（在chrome浏览器中样式不对）

**Comment by pattybaby110** [comment]
<img width="218" alt="image" src="https://user-images.githubusercontent.com/88708072/205842855-d700297b-ed68-4c0a-b2a1-9d10f7c5b064.png">
这里的icon 特别是搜索和人员 感觉不够平滑，其中人员的感觉弧度也有问题
