### ISSUE TITLE
组件【cascader 级联选择器】设计优化

### ISSUE THREAD

**Issue by eugenewoody** [Tencent/tdesign#145]
### 这个功能解决了什么问题

解决开发组件和设计稿样式没对齐的问题。（备注：本次修改建议在menu修改完成之后进行）

### 你建议的方案是什么
一、【组件cascader级联选择器】codesign地址：https://codesign.qq.com/s/zm5q0Xq556ZRBb6
访问密码：6K8C
二、【组件cascader级联选择器】figma源文件地址：https://www.figma.com/file/KInDIZzoxifaKVQ3n5KB8W/TDesign-for-web?node-id=46279%3A339149
三、具体修改细节如下（详见图片）：
<img width="2264" alt="cas" src="https://user-images.githubusercontent.com/103838357/177906951-1ec3e1f8-e555-492e-a124-6057e82f715a.png">
1.级联选择器的【下拉菜单】圆角参数不对，应该为6。padding数值不对，中尺寸为6，小尺寸为4，大尺寸为8。margin数值不对，应为2。
2.下拉菜单选中态、悬浮态的高度不对，中尺寸为28，小尺寸为22，大尺寸为36。
3.下拉菜单中的信息没有居中对齐。
4.级联选择器输入框的padding不对，中尺寸/小尺寸为8，大尺寸为12。
5.级联选择器多选输入框的padding不对，应为4。
6.级联选择器下拉菜单有【描边】。样式：gray4，inside，0.5。
备注：级联选择器中下拉菜单样式应与组件【下拉菜单】样式保持一致。

**Comment by zhangpaopao0609** [comment]
认领

**Comment by zhangpaopao0609** [comment]
处理中

**Comment by zhangpaopao0609** [comment]
. 圆角无误；padding 已修复；margin 已修复
2. 高度无误
3. 居中修复
4. 使用的是 select，因此需要在 select 中修复
5. 使用的是 select，因此需要在 select 中修复
6. 使用的是 select，因此需要在 select 中修复
