### ISSUE TITLE
组件【select 选择器】样式优化

### ISSUE THREAD

**Issue by eugenewoody** [Tencent/tdesign#148]
### 这个功能解决了什么问题

解决开发样式和设计样式没有对齐的问题（备注：本次修改建议在组件【cascader】修改完成之后进行）

### 你建议的方案是什么

一、【组件 select选择器】codesign地址：
https://codesign.qq.com/s/ALwE9VKLvA0X1Dp/qxWyZ1Jy4kjmVXk/inspect
访问密码：CUOA
二、【组件select 选择器】figma源文件地址：https://www.figma.com/file/KInDIZzoxifaKVQ3n5KB8W/TDesign-for-web?node-id=30856%3A112056
三、具体修改细节如下（详见图片）：
<img width="2264" alt="组select截图" src="https://user-images.githubusercontent.com/103838357/178207761-f87df4d8-fb9a-48af-83eb-0e3dfc945cac.png">
【问题1】下拉菜单缺少描边。
【方案1】描边样式为：gray4/0.5/inside。
【问题2】多选选择器，选中态字体颜色不对。
【方案2】应为brand8-normal。
【问题3】分组选择器，分割线的margin和padding不对。
【方案3】间距为2。分割线的padding为2，8，2，8。
【问题4】分组选择器，下拉菜单中，【分组】的样式透明度不对。
【方案4】应为26%。
【问题5】大尺寸输入框padding不对。
【方案5】应为12。
【问题6】大/中尺寸输入框中字号不对。
【方案6】分别应为16、14。
【建议7】【不同尺寸的选择器】中，建议小尺寸的下拉菜单为240，即与输入框保持一致。
【问题8】下拉菜单中，选中项没有居中对齐。
【方案8】文字纵向需居中对齐。
【问题9】自定义下拉选项选择器样式不对。
【方案9】下拉菜单选项中，内容区上下padding应为3。
【问题10】自定义面板选择器，下拉菜单选中态的padding不对。
【方案10】选中态的padding为8，且状态为【fill】，而不是hug。
【问题11】自定义选中项选择器，输入框高度不对。
【方案11】应为32。
【问题12】大尺寸中下拉菜单中，选中态的padding不对。
【方案12】padding值为6，12，6，12。

**Comment by guoaihua** [comment]
认领该任务，预计7-10日完成
