### ISSUE TITLE
组件【collapse 折叠面板】样式优化

### ISSUE THREAD

**Issue by eugenewoody** [Tencent/tdesign#152]
### 这个功能解决了什么问题

解决开发样式和设计样式没有对齐的问题（备注：本次修改建议在【select 选择器】修改完成之后进行）

### 你建议的方案是什么

一、【组件collapse 折叠面板】codesign地址：https://codesign.qq.com/s/2nL6jgkLqmjpJXV/wRap9xdQ1k9r4gN/inspect
访问密码：OLZL
二、【组件collapse 折叠面板】figma源文件地址：https://www.figma.com/file/KInDIZzoxifaKVQ3n5KB8W/TDesign-for-web?node-id=27782%3A86787
三、具体修改细节如下（详见图片）：
<img width="2264" alt="【collapse 折叠画板】" src="https://user-images.githubusercontent.com/103838357/179156479-1d90b036-3aae-4e6a-b46b-57cb9def1af4.png">
【问题1】展开内容的字体颜色不对。
【方案1】字体颜色应为#000000，60%（Font Gy2 60%-secondary）。
【问题2】展开/收起箭头缺少hover态。
【方案2】hover态样式：大小16*16，radius-small:3px, 颜色为gray1。
【问题3】禁用样式不对。
【方案3】禁用样式容器背景颜色为white1，禁用态文字及箭头的颜色为#000000，26%（Font Gy4 26%-disabled）。
【问题4】收起箭头的方向不对。（出现于Safari页面）
【方案4】收起箭头的方向应朝下。

**Comment by ZWkang** [comment]
@eugenewoody 我来做这个，备注的select组件是否已经完成修改了？

**Comment by zhangpaopao0609** [comment]
> @eugenewoody 我来做这个，备注的select组件是否已经完成修改了？

抱歉哈，因为一些原因这个需要我这儿完成但是又忘记认领了，所以抱歉了

**Comment by zhangpaopao0609** [comment]
1. 字体颜色修复
2. 箭头 hover 修复
3. 禁用背景颜色和文字箭头颜色修复
4. 箭头方向 safari 沟通后暂不修复，后面统一修复

**Comment by ZWkang** [comment]
ok
