### ISSUE TITLE
组件【comment 评论】样式优化

### ISSUE THREAD

**Issue by eugenewoody** [Tencent/tdesign#155]
### 这个功能解决了什么问题

解决开发样式和设计样式没有对齐的问题（备注：本次修改建议在【collapse 折叠面板】修改完成之后进行）

### 你建议的方案是什么

一、【组件 Comment评论】codesign地址：
https://codesign.woa.com/s/kv8398VAgVZnKeg
访问密码：SG8A
二、【组件 Comment评论】figma源文件地址：https://www.figma.com/file/KInDIZzoxifaKVQ3n5KB8W/TDesign-for-web?node-id=48167%3A516148
三、具体修改意见下图：
![comment截图](https://user-images.githubusercontent.com/103838357/180696553-d109011e-7f3a-4162-87ac-a9cc414265f0.png)

**Comment by AvenirZheng** [comment]
codesign 网址无法访问

**Comment by zhangpaopao0609** [comment]
认领

**Comment by SlaterVanS** [comment]
领取

**Comment by zhangpaopao0609** [comment]
1. 字体大小无误待确认；对齐方式已修复
2. 色值无误待确认；小图标待确认（因为所有的图标都是用户引入的，组件负责渲染）
3. 24 距离无误待确认
4. 居中对齐已修复
5. margin 16 已修复
6. 这里的实现方式为使用 t-list，所以按照现在的设计上下的间距（现为 12）无法调整
7. 这里的实现方式为使用 t-comment，所以按现在的设计无法改变色值，但可以设置一个透明度
8. 图标为用户引入，组件无法干涉
