### ISSUE TITLE
Edge浏览器 下首页卡顿

### ISSUE THREAD

**Issue by WhenLeo** [Tencent/tdesign#159]
### tdesign 版本

**

### 重现链接

https://tdesign.tencent.com/

### 重现步骤

首页卡顿：https://tdesign.tencent.com/
浏览器：Microsof edge
版本： 
<img width="332" alt="image" src="https://user-images.githubusercontent.com/17340591/182517793-68e82805-2afd-4dbf-9ef8-ef04a14eae25.png">
操作系统（电脑）：
<img width="198" alt="image" src="https://user-images.githubusercontent.com/17340591/182517863-c42f674b-0028-4327-baef-4651914a4b2c.png">

### 浏览器版本

Edge 103.0.1264.62 (正式版本) (arm64)

### 系统版本

MacOS 12.5

**Comment by xiaosansiji** [comment]
可以多提供些信息：
- 浏览器 lighthouse 数据
- 必要的录屏
等帮助排查下问题么？
