### ISSUE TITLE
[招募][Figma] Dropdown item prototype 原型动画设计

### ISSUE THREAD

**Issue by Wen1kang** [Tencent/tdesign#169]
### Figma 设计资源 Prototype 设计

**🔥 长期招募贡献者设计并维护 Figma Prototype**

### Dropdown 下拉菜单

Figma **下拉菜单各级选项**需要增加 Prototype 交互效果，方便各角色同学搭建设计系统进行 Demo 演示。

<img width="611" alt="image" src="https://user-images.githubusercontent.com/89069385/184823996-80a6f71f-80f5-436b-94b3-380eb7023765.png">

#

### Tips

- 需要有 Figma 使用经验的设计同学参与，**中难度**
- 认领任务前联系，可以进行前期沟通

![位图](https://user-images.githubusercontent.com/89069385/184820174-7adc4caf-624a-4924-bbc0-948f521f080c.png)

### 激励

- 参与共建的开发者，将可以获得 [TDesign 周边](https://github.com/Tencent/tdesign/wiki/TDesign-%E5%91%A8%E8%BE%B9)（贴纸、鼠标垫、工卡套等）；
- 成为核心贡献者，将会拥有 TDesign 专属头像。

**Comment by CRECOHE** [comment]
领取

**Comment by Wen1kang** [comment]
已完成，感谢 @CRECOHE
