### ISSUE TITLE
Layout API 是否考虑增加 className 和 style 的字段

### ISSUE THREAD

**Issue by cuijinyu** [Tencent/tdesign#17]
**Is your feature request related to a problem? Please describe.**
目前 layout 并不支持对容器的直接 class 和 样式 的改变
在使用时会有较大的疑惑
目前在改变时需要内部容器撑起 或 覆盖 css

![image](https://user-images.githubusercontent.com/22697021/147623810-f0475393-d2f4-45c6-a914-669a914b2aa9.png)

**Describe the solution you'd like**
为 layout 增加 className 和 style 的属性

**Comment by chaishi** [comment]
@HQ-Lin  React 组件，默认情况全部支持 `className` 和 `style`，如果不支持需要补上

**Comment by HQ-Lin** [comment]
> @HQ-Lin React 组件，默认情况全部支持 `className` 和 `style`，如果不支持需要补上

https://github.com/Tencent/tdesign-react/blob/develop/src/layout/Layout.tsx#L58
默认支持的，只是 api 一般不体现这类基础 dom 属性

**Comment by HQ-Lin** [comment]
https://codesandbox.io/s/tdesign-react-demo-forked-6jwzq?file=/src/demo.jsx
能提供简单的在线demo 复现一下嘛，我这边传递 className style 正常

**Comment by cuijinyu** [comment]
可以在API文档和TS类型定义中增加下~ 使用者感知不强

**Comment by chaishi** [comment]
> React 组件库，默认情况全部支持 className 和 style

全部都写一遍 和 直接告诉大家我们都支持，效果差不多。我们后续考虑下
