### ISSUE TITLE
[招募][Figma] Menu prototype 原型动画设计

### ISSUE THREAD

**Issue by Wen1kang** [Tencent/tdesign#170]
### Figma 设计资源 Prototype 设计

**🔥 长期招募贡献者设计并维护 Figma Prototype**

### Menu 导航菜单

Figma 导航菜单需要增加 Prototype 交互效果，方便各角色同学搭建设计系统进行 Demo 演示。

- 侧边导航栏切换交互状态
- 侧边导航各层级选项交互状态
- 顶部导航栏切换交互状态
- 顶部导航栏菜单各选项交互状态

<img width="651" alt="image" src="https://user-images.githubusercontent.com/89069385/184827343-e5850d82-ed60-4787-b175-e80289fd222e.png">
<img width="634" alt="image" src="https://user-images.githubusercontent.com/89069385/184827432-c494da19-cf6c-43b1-a63f-3e16b7c6aac3.png">
<img width="826" alt="image" src="https://user-images.githubusercontent.com/89069385/184827763-2784e351-b8d2-4050-ab16-96dadfe47894.png">
<img width="552" alt="image" src="https://user-images.githubusercontent.com/89069385/184827825-08cd692e-515f-4d05-8b1c-bef9e5d4a6b8.png">

#

### Tips

- 需要有 Figma 使用经验的设计同学参与，**高难度**
- 认领任务前联系，可以进行前期沟通

![位图](https://user-images.githubusercontent.com/89069385/184820174-7adc4caf-624a-4924-bbc0-948f521f080c.png)

### 激励

- 参与共建的开发者，将可以获得 [TDesign 周边](https://github.com/Tencent/tdesign/wiki/TDesign-%E5%91%A8%E8%BE%B9)（贴纸、鼠标垫、工卡套等）；
- 成为核心贡献者，将会拥有 TDesign 专属头像。

**Comment by CRECOHE** [comment]
领取

**Comment by Wen1kang** [comment]
已完成，感谢 @CRECOHE
