### ISSUE TITLE
[招募][Figma] ColorPicker Variant 变体设计

### ISSUE THREAD

**Issue by Wen1kang** [Tencent/tdesign#171]
### Figma 设计资源 Variant 设计

**🔥 长期招募贡献者设计并维护 Figma Variant**

### ColorPicker 颜色选择器

Figma 颜色选择器需要完成 Variant 变体设计，对齐已有组件设计

- 组件类型对应开发 API
- 组件交互状态

<img width="456" alt="image" src="https://user-images.githubusercontent.com/89069385/184842399-2257ce07-e26f-422e-852c-f6ca1db8cf27.png">

#

### Tips

- 需要有 Figma 使用经验的设计同学参与，**高难度**
- 认领任务前联系，可以进群进行前期沟通，使用微信或企业微信扫码加入

<img width="280" alt="Snipaste_2022-08-31_17-58-49" src="https://user-images.githubusercontent.com/89069385/187654607-2695d1db-8327-42bb-a03d-6b40a2affd59.png">

### 激励

- 参与共建的开发者，将可以获得 [TDesign 周边](https://github.com/Tencent/tdesign/wiki/TDesign-%E5%91%A8%E8%BE%B9)（贴纸、鼠标垫、工卡套等）；
- 成为核心贡献者，将会拥有 TDesign 专属头像。

**Comment by Lido8** [comment]
认领

**Comment by Wen1kang** [comment]
已完成，感谢 @Lido8
