### ISSUE TITLE
[招募][Figma] Timeline 时间轴 Variant 变体设计

### ISSUE THREAD

**Issue by Wen1kang** [Tencent/tdesign#175]
### Figma 设计资源 Variant 设计

**🔥 长期招募贡献者设计并维护 Figma Variant**

### Timeline 时间轴

Figma 时间轴需要完成 Variant 变体设计，对齐已有组件设计

- 组件类型对应开发 API
- 组件交互状态
- 规范化图层命名

<img width="925" alt="image" src="https://user-images.githubusercontent.com/89069385/184851071-c2279c43-b0ce-40fd-ac73-53eecd0158d0.png">

#

### Tips

- 需要有 Figma 使用经验的设计同学参与，**高难度**
- 认领任务前联系，可以进行前期沟通

![位图](https://user-images.githubusercontent.com/89069385/184820174-7adc4caf-624a-4924-bbc0-948f521f080c.png)

### 激励

- 参与共建的开发者，将可以获得 [TDesign 周边](https://github.com/Tencent/tdesign/wiki/TDesign-%E5%91%A8%E8%BE%B9)（贴纸、鼠标垫、工卡套等）；
- 成为核心贡献者，将会拥有 TDesign 专属头像。

**Comment by yupengcui** [comment]
已认领

**Comment by Wen1kang** [comment]
已完成，感谢 @yupengcui
