### ISSUE TITLE
[招募][Figma] Tooltip 文字提示 新增 Variant 变体类型

### ISSUE THREAD

**Issue by Wen1kang** [Tencent/tdesign#176]
### Figma 设计资源 Variant 设计

**🔥 长期招募贡献者设计并维护 Figma Variant**

### Tooltip 文字提示

Figma 文字提示新增跟随鼠标类型，需要同步完成 Variant 设计

- 组件类型对应开发 API
- 组件交互状态

<img width="400" alt="image" src="https://user-images.githubusercontent.com/89069385/184852534-97792c8f-6678-4c8f-a0c1-ec59aa694788.png">

#

### Tips

- 需要有 Figma 使用经验的设计同学参与，**低难度**
- 认领任务前联系，可以进行前期沟通

![位图](https://user-images.githubusercontent.com/89069385/184820174-7adc4caf-624a-4924-bbc0-948f521f080c.png)

### 激励

- 参与共建的开发者，将可以获得 [TDesign 周边](https://github.com/Tencent/tdesign/wiki/TDesign-%E5%91%A8%E8%BE%B9)（贴纸、鼠标垫、工卡套等）；
- 成为核心贡献者，将会拥有 TDesign 专属头像。

**Comment by Alimjan2013** [comment]
我认领

**Comment by Wen1kang** [comment]
已完成，感谢 @Alimjan2013
