### ISSUE TITLE
[招募][Sketch] ColorPicker 颜色选择器 组件设计入库

### ISSUE THREAD

**Issue by Wen1kang** [Tencent/tdesign#177]
### Sketch 设计资源组件设计

**🔥 长期招募贡献者设计并维护 Sketch 样式和Symbol**

### ColorPicker 颜色选择器

Sketch 颜色选择器需要完成组件设计入库，对齐已有 Figma 资源组件设计

- 组件类型 Symbol 化
- 规范组件样式
- 规范图层命名

<img width="456" alt="image" src="https://user-images.githubusercontent.com/89069385/184842399-2257ce07-e26f-422e-852c-f6ca1db8cf27.png">

#

### Tips

- 需要有 Sketch 使用经验的设计同学参与，**中难度**
- 认领任务前联系，可以进行前期沟通

![位图](https://user-images.githubusercontent.com/89069385/184820174-7adc4caf-624a-4924-bbc0-948f521f080c.png)

### 激励

- 参与共建的开发者，将可以获得 [TDesign 周边](https://github.com/Tencent/tdesign/wiki/TDesign-%E5%91%A8%E8%BE%B9)（贴纸、鼠标垫、工卡套等）；
- 成为核心贡献者，将会拥有 TDesign 专属头像。

**Comment by minrongh** [comment]
领取

**Comment by Wen1kang** [comment]
已完成，感谢 @minrongh
