### ISSUE TITLE
[招募][Sketch] Card 卡片 组件设计入库 

### ISSUE THREAD

**Issue by Wen1kang** [Tencent/tdesign#179]
### Sketch 设计资源组件设计

**🔥 长期招募贡献者设计并维护 Sketch 样式和Symbol**

### Card 卡片

Sketch 卡片需要完成资源入库，对齐已有 Figma 资源组件设计

- 组件类型 Symbol 化
- 规范组件样式
- 规范图层命名

<img width="405" alt="image" src="https://user-images.githubusercontent.com/89069385/184865981-79e11f7f-3470-43eb-b7d8-db60e13f38cb.png">

#

### Tips

- 需要有 Sketch 使用经验的设计同学参与，**中难度**
- 认领任务前联系，可以进行前期沟通

![位图](https://user-images.githubusercontent.com/89069385/184820174-7adc4caf-624a-4924-bbc0-948f521f080c.png)

### 激励

- 参与共建的开发者，将可以获得 [TDesign 周边](https://github.com/Tencent/tdesign/wiki/TDesign-%E5%91%A8%E8%BE%B9)（贴纸、鼠标垫、工卡套等）；
- 成为核心贡献者，将会拥有 TDesign 专属头像。

**Comment by keson1521** [comment]
认领
