### ISSUE TITLE
【官网】设计-色彩-功能色 展示丢了几个字段

### ISSUE THREAD

**Issue by pattybaby110** [Tencent/tdesign#18]
**Is your feature request related to a problem? Please describe.**
官网-设计-色彩-功能色，丢了几个字段

**Describe the solution you'd like**
red是6，orange是5，green是5

![image](https://user-images.githubusercontent.com/88708072/147634078-c2a14616-434e-42b8-bcc3-766970ec719f.png)

**Comment by HQ-Lin** [comment]
![image](https://user-images.githubusercontent.com/24469546/147659377-ee6cf6c5-328b-491b-8607-1adb8a670b9e.png)
fixed.
