### ISSUE TITLE
[招募][视觉设计] Guide引导 组件设计

### ISSUE THREAD

**Issue by Wen1kang** [Tencent/tdesign#183]
### Guide 引导

根据组件交互稿，完成 Guide 引导 组件视觉设计

- 组件类型实例
- 规范组件样式
- 规范图层命名

<img width="1186" alt="image" src="https://user-images.githubusercontent.com/89069385/184870801-3dbb307c-d45b-4294-af72-bec26f57fead.png">

### 交互稿

https://codesign.qq.com/s/2nL6jgkLqmjpJXV/RG6X0kRdLVb9xEP/inspect
访问密码：OLZL

#

### Tips

- 建议使用 Figma 进行设计，设计工具限制为Figma/Sketch/XD，**中难度**
- 认领任务前联系，可以进行前期沟通

![位图](https://user-images.githubusercontent.com/89069385/184820174-7adc4caf-624a-4924-bbc0-948f521f080c.png)

### 激励

- 参与共建的开发者，将可以获得 [TDesign 周边](https://github.com/Tencent/tdesign/wiki/TDesign-%E5%91%A8%E8%BE%B9)（贴纸、鼠标垫、工卡套等）；
- 成为核心贡献者，将会拥有 TDesign 专属头像。

**Comment by eugenewoody** [comment]
我认领
