### ISSUE TITLE
组件【Table 表格】样式优化

### ISSUE THREAD

**Issue by eugenewoody** [Tencent/tdesign#189]
### 这个功能解决了什么问题

解决开发样式和设计样式没有对齐的问题（备注：本次修改建议在【comment 评论】修改完成之后进行）

### 你建议的方案是什么

一、【组件Table 表格】codesign地址：https://codesign.qq.com/s/ALwE9VKLvA0X1Dp
访问密码：CUOA
二、【组件Table 表格】figma地址源文件：https://www.figma.com/file/KInDIZzoxifaKVQ3n5KB8W/TDesign-for-web?node-id=46868%3A353120
三、具体修改细节如下（详见图片）：
![table](https://user-images.githubusercontent.com/103838357/185924557-7b45cf6c-5e44-47c0-9e65-3ffae02c88d8.png)

**Comment by zhangpaopao0609** [comment]
处理中

**Comment by zhangpaopao0609** [comment]
1. 第二个 padding 8 是由 size small 导致的

**Comment by zhangpaopao0609** [comment]
经确认
2. 保留圆角
3. 修改成 border
7. 不修改
9. 按照设计稿修复即可
