### ISSUE TITLE
组件【Tag 标签】样式优化

### ISSUE THREAD

**Issue by eugenewoody** [Tencent/tdesign#190]
### 这个功能解决了什么问题

解决开发样式和设计样式没有对齐的问题（备注：本次修改建议在【table 表格】修改完成之后进行）

### 你建议的方案是什么

一、【组件tag 标签】codesign地址：https://codesign.qq.com/s/ALwE9VKLvA0X1Dp
访问密码：CUOA
二、【组件tag 标签】figma地址源文件：https://www.figma.com/file/KInDIZzoxifaKVQ3n5KB8W/TDesign-for-web?node-id=31256%3A112577
三、具体修改细节如下（详见图片）：
![tag](https://user-images.githubusercontent.com/103838357/185926210-3f2d534e-531d-43a1-be32-f5ee20c894c6.png)

**Comment by wangchong1994** [comment]
处理中
