### ISSUE TITLE
组件【Popconfirm 气泡确认框】样式优化 

### ISSUE THREAD

**Issue by eugenewoody** [Tencent/tdesign#191]
### 这个功能解决了什么问题

解决开发样式和设计样式没有对齐的问题（备注：本次修改建议在【tag 标签】修改完成之后进行）

### 你建议的方案是什么

一、【组件Popconfirm 气泡确认框】codesign地址：https://codesign.qq.com/s/ALwE9VKLvA0X1Dp
访问密码：CUOA
二、【组件Popconfirm 气泡确认框】figma地址源文件：https://www.figma.com/file/KInDIZzoxifaKVQ3n5KB8W/TDesign-for-web?node-id=45434%3A322799
三、具体修改细节如下（详见图片）：
![popconfirm](https://user-images.githubusercontent.com/103838357/185927609-8ae58839-2855-4956-bbe3-795375f1ed6c.png)

**Comment by zhangpaopao0609** [comment]
处理中
