### ISSUE TITLE
[招募][Figma] WaterMark 水印组件标准化设计

### ISSUE THREAD

**Issue by Wen1kang** [Tencent/tdesign#197]
### Figma 设计资源 组件标准化设计

**🔥 长期招募贡献者设计并维护 Figma 设计资源**

### Rate 评分

Figma 水印组件需要完成标准化设计

- 组件 symbol 化
- 组件 AutoLayout 设定
- 示例对齐开发内容

<img width="624" alt="image" src="https://user-images.githubusercontent.com/89069385/187617894-3f962266-68d5-4085-84f2-cfab76e023c0.png">

#

### Tips

- 需要有 Figma 使用经验的设计同学参与，**中难度**
- 认领任务前联系，可以进群进行前期沟通，使用微信或企业微信扫码加入

<img width="280" alt="Snipaste_2022-08-31_17-58-49" src="https://user-images.githubusercontent.com/89069385/187654607-2695d1db-8327-42bb-a03d-6b40a2affd59.png">

### 激励

- 参与共建的开发者，将可以获得 [TDesign 周边](https://github.com/Tencent/tdesign/wiki/TDesign-%E5%91%A8%E8%BE%B9)（贴纸、鼠标垫、工卡套等）；
- 成为核心贡献者，将会拥有 TDesign 专属头像。

**Comment by turkyden** [comment]
1

**Comment by Wen1kang** [comment]
@turkyden 不好意思晚了一步，已有同学认领咯～

**Comment by turkyden** [comment]
okk

**Comment by bruce0222** [comment]
已认领

**Comment by Wen1kang** [comment]
已完成，感谢 @bruce0222
