### ISSUE TITLE
[招募][Sketch] Table 表格 组件设计入库

### ISSUE THREAD

**Issue by Wen1kang** [Tencent/tdesign#198]
### Sketch 设计资源组件设计

**🔥 长期招募贡献者设计并维护 Sketch 样式和Symbol**

### Table 表格

Sketch 表格需要完成组件设计入库，对齐已有 Figma 资源组件设计

- 组件类型 Symbol 化
- 规范组件样式
- 规范图层命名

<img width="555" alt="image" src="https://user-images.githubusercontent.com/89069385/187621200-50f94644-c4d2-4a17-b95e-51e4731c5bd8.png">

#

### Tips

- 需要有 Sketch 使用经验的设计同学参与，**中难度**
- 认领任务前联系，可以进群进行前期沟通，使用微信或企业微信扫码加入

<img width="280" alt="Snipaste_2022-08-31_17-58-49" src="https://user-images.githubusercontent.com/89069385/187654607-2695d1db-8327-42bb-a03d-6b40a2affd59.png">

### 激励

- 参与共建的开发者，将可以获得 [TDesign 周边](https://github.com/Tencent/tdesign/wiki/TDesign-%E5%91%A8%E8%BE%B9)（贴纸、鼠标垫、工卡套等）；
- 成为核心贡献者，将会拥有 TDesign 专属头像。

**Comment by burtonx** [comment]
已领取

**Comment by Wen1kang** [comment]
已完成
