### ISSUE TITLE
[Breadcrumb] 带图标面包屑没有居中

### ISSUE THREAD

**Issue by Wen1kang** [Tencent/tdesign#212]
### tdesign 版本

Vue2 0.46.3｜Vue3 0_20_4｜React 0.40.6

### 期望结果

<img width="831" alt="image" src="https://user-images.githubusercontent.com/89069385/188868983-511b737c-9c3f-49e1-8da2-f300db132a7d.png">

### 实际结果

目前是偏下的

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/89069385/188869158-1515daae-6d7f-4885-bdf5-5b1a9a93f8b3.png">

### 框架版本

Vue2 0.46.3｜Vue3 0_20_4｜React 0.40.6

**Comment by Micro-sun** [comment]
认领。
