### ISSUE TITLE
[Steps] demo文案错误

### ISSUE THREAD

**Issue by Wen1kang** [Tencent/tdesign#218]
### tdesign 版本

Vue2 0.46.3｜Vue3 0_20_4｜React 0.40.6

### 实际结果

垂直步骤条的demo文案错误，进行中、未进行和已完成示意不对

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/89069385/189054513-7c00b8f2-7da7-4fce-8665-bb11a7e937d7.png">

### 框架版本

Vue2 0.46.3｜Vue3 0_20_4｜React 0.40.6

**Comment by Micro-sun** [comment]
认领。
