### ISSUE TITLE
[Radio] 按钮组描边型样式不对和小尺寸item的左右padding修改

### ISSUE THREAD

**Issue by Wen1kang** [Tencent/tdesign#221]
### tdesign 版本

Vue2 0.46.3｜Vue3 0_20_4｜React 0.40.6

### 1.描边型单选按钮组样式不对

- **高度不对**，不是继承面性按钮的选项高度的，小尺寸应该是24px，中尺寸32px，大尺寸40px
- **圆角不对**，选项的原本左右圆角不是继承面性的圆角，而是由最外层的圆角覆盖

### 2.小型的单选按钮组选项的padding需要修改为8px

详情查看CoDesign：https://codesign.qq.com/s/ALwE9VKLvA0X1Dp/2nL6jgkXpoKjpJX/inspect  访问密码：CUOA

<img width="723" alt="image" src="https://user-images.githubusercontent.com/89069385/189085217-0db6cc99-b52c-4cbd-a131-35060c091134.png">

### 实际结果

<img width="1214" alt="image" src="https://user-images.githubusercontent.com/89069385/189087505-c6689e6f-3734-40f9-9870-97a4af0cdaab.png">

<img width="243" alt="image" src="https://user-images.githubusercontent.com/89069385/189087608-8132c2ee-aad9-43aa-b77a-d7992206de22.png">

### 框架版本

Vue2 0.46.3｜Vue3 0_20_4｜React 0.40.6

**Comment by Micro-sun** [comment]
认领。
