### ISSUE TITLE
[RangeInput] 大尺寸的padding不对

### ISSUE THREAD

**Issue by Wen1kang** [Tencent/tdesign#222]
### tdesign 版本

Vue2 0.46.3｜Vue3 0_20_4｜React 0.40.6

### 期望结果

**应该上下的padding是4px，现在是8px**

<img width="849" alt="image" src="https://user-images.githubusercontent.com/89069385/189089671-7f308a0e-a70b-41a0-93cf-fd4e11a29f7d.png">

### 实际结果

<img width="1525" alt="image" src="https://user-images.githubusercontent.com/89069385/189089323-10d31f73-2036-42be-be6a-2365c8623a65.png">

### 框架版本

Vue2 0.46.3｜Vue3 0_20_4｜React 0.40.6

**Comment by Isabella327** [comment]
认领
