### ISSUE TITLE
[Select] 样式问题集合

### ISSUE THREAD

**Issue by Wen1kang** [Tencent/tdesign#226]
### tdesign 版本

Vue2 0.46.3｜Vue3 0_20_4｜React 0.40.6

### 1.展开选项没居中对齐

- 中尺寸line height不对导致没居中对齐，应该是22px

### 2.分组选择器样式不对

- 选项应该是和标题对齐的
- 选项与分组标题的间距都是相同的

<img width="320" alt="image" src="https://user-images.githubusercontent.com/89069385/189107040-6dfb932a-6480-4f4c-b081-12f5c36c5c0f.png">

### 3.分割线样式不对

- 长度不对应该与文字对齐
- 上下margin不对

<img width="320" alt="image" src="https://user-images.githubusercontent.com/89069385/189107858-987a8eb7-bc91-40ae-8928-9d2db882df02.png">

### 4.自定义下拉选项demo展示问题

- 自定义的item padding需要修改为8px
- item的设置的高度设置为100%

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/89069385/189109665-33264c26-fa8e-46b3-bc43-85d73e182e6a.png">

### 5.自定义下拉面板demo展示问题

- 第一个插入的 textarea 增加padding`padding:6px 6px 0px 6px`
- 第二个插入footer删除margin-top，padding修改为6px，border颜色修改@component-stroke；按钮修改并修改为带icon的block按钮，icon引用`add`

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/89069385/189113299-8a81b992-fb3d-4ddf-9d09-f7f180a386b9.png">

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/89069385/189113924-1e92e98c-e78c-4b55-8117-19d4aaabb943.png">

### 6.有前缀图标的选择器icon大小不对

- 图标大小应该为16px

<img width="200" alt="image" src="https://user-images.githubusercontent.com/89069385/189114583-5700ca14-f577-455c-834a-a429a55e6cfa.png">

### 7.自适应宽度的select，suffix icon的左margin不生效

- 应该是距离内容有8px的间距

<img width="280" alt="image" src="https://user-images.githubusercontent.com/89069385/189116346-228d350a-05c8-4d50-8473-ba3c72752387.png">

参考Codesign：
https://codesign.qq.com/s/ALwE9VKLvA0X1Dp/qxWyZ1Jy4kjmVXk/inspect
访问密码：CUOA

### 框架版本

Vue2 0.46.3｜Vue3 0_20_4｜React 0.40.6

**Comment by HQ-Lin** [comment]
4、5 是demo 展示问题，需调整demo
