### ISSUE TITLE
[TreeSelect] 菜单样式不对

### ISSUE THREAD

**Issue by Wen1kang** [Tencent/tdesign#229]
### tdesign 版本

Vue2 0.46.3｜Vue3 0_20_4｜React 0.40.6

### 1. Popup需要增加整体6px的padding
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/89069385/189124391-e02ed044-9396-4fec-b6fd-0d9f77186db5.png">

### 2. 批示文字左间距应该8px
<img width="1706" alt="image" src="https://user-images.githubusercontent.com/89069385/189124278-c11003f0-0e28-42b2-9c65-f8cfa8400f7e.png">

### 框架版本

Vue2 0.46.3｜Vue3 0_20_4｜React 0.40.6

**Comment by fenbitou** [comment]
1. 针对问题 1，在 Select 组件 Vue2, Vue3 版中， treeSelect 完全无 padding，可以通过
`          `${this.componentName}__dropdown-inner`,
            `${this.componentName}__dropdown-inner--size-${sizeClassMap[size]}`,`  类名，对于不同的大小。添加了 6px, 8px, 4px 的 padding，符合要求 1 。
    但是，在 React 中，由于结构实现不一致，该组件回落至使用 t-popup__content 样式，即 padding: 4px 8px;
   那这个问题应当是全部统一成 根据组件 size ，显示不同的 padding？

**Comment by fenbitou** [comment]
Vue2 & Vue3 已修改
