### ISSUE TITLE
[Pagination] hover 状态无过度动画

### ISSUE THREAD

**Issue by Wen1kang** [Tencent/tdesign#231]
### tdesign 版本

Vue2 0.46.3｜Vue3 0_20_4｜React 0.40.6

### 期望结果

增加hover过渡动画，目前过渡效果生硬

### 框架版本

Vue2 0.46.3｜Vue3 0_20_4｜React 0.40.6

**Comment by jiazengp** [comment]
认领 @xiaosansiji

**Comment by zhangpaopao0609** [comment]
> 认领 @xiaosansiji

抱歉了，因为一些原因需要我这儿处理，但又忘记认领了，抱歉抱歉！！
