### ISSUE TITLE
[Slider] 样式问题合集

### ISSUE THREAD

**Issue by eugenewoody** [Tencent/tdesign#237]
### tdesign 版本

Vue2 0.47.0｜Vue3 0_21_0｜React 0.41.1

### 1.游标缺少阴影
· 游标的阴影为--td-shadow-1
### 2.水平、垂直方向的首尾刻度线在滑动轴位置不对
·首尾刻度线应与滑动轴两端保持4的间距
<img width="1413" alt="截屏2022-09-19 15 42 44" src="https://user-images.githubusercontent.com/103838357/190972008-9a1dcc97-187f-49f3-89f6-b0d61f991d17.png">
### 3.React框架下，设置【最大值】【最小值】，无文案显示。
<img width="901" alt="截屏2022-09-19 15 58 55" src="https://user-images.githubusercontent.com/103838357/190974237-3eb0690a-d0a8-4934-9723-68034071df5a.png">

**Comment by xiaosansiji** [comment]
问题2: 
<img width="1642" alt="企业微信截图_c0f7dcc3-64f9-4a0b-b4f2-56fd7abb2802" src="https://user-images.githubusercontent.com/7600149/196388170-72e889ad-c5ac-4df5-acf6-298e705f5e29.png">
暂不更改，倾向选择方案3，等待 @Wen1kang 更新设计稿后继续修改
