### ISSUE TITLE
[TimePicker] 样式问题合集

### ISSUE THREAD

**Issue by eugenewoody** [Tencent/tdesign#239]
### tdesign 版本

Vue2 0.47.0｜Vue3 0_21_0｜React 0.41.1

### 1.下拉弹窗中，分割线宽度不对。
·分割线宽度和弹窗宽度保持一致，不存在边距。
<img width="332" alt="截屏2022-09-20 11 24 40" src="https://user-images.githubusercontent.com/103838357/191160625-18e8d9ef-8ddc-422a-8c65-6879caf70421.png">
### 2.下拉弹窗中，button（左右）与弹窗的边距不对。
·边距应为12。

**Comment by xiaosansiji** [comment]
该问题已经修复，可以查看各技术栈最新官网
