### ISSUE TITLE
[Avatar] 样式问题合集

### ISSUE THREAD

**Issue by eugenewoody** [Tencent/tdesign#242]
### tdesign 版本

Vue2 0.47.0｜Vue3 0_21_0｜React 0.41.1

### 期望结果

_**demo**_
### 1.头像类型展示有重复
·需要删除，同时建议视觉展示顺序和文案描述顺序一致。
<img width="1018" alt="截屏2022-09-21 11 05 40" src="https://user-images.githubusercontent.com/103838357/191406009-2119bbb3-9e78-4e5f-a819-1933be1762a5.png">

**Comment by xiaosansiji** [comment]
最后一个重复的需要删除，其他的出现顺序按照文字顺序调整。Vue2/Vue next/React 三个仓库需要分别提 PR 修改 demo 代码
