### ISSUE TITLE
[Calender] 样式问题合集

### ISSUE THREAD

**Issue by eugenewoody** [Tencent/tdesign#244]
### tdesign 版本

Vue2 0.47.0｜Vue3 0_21_0｜React 0.41.1

### 期望结果

组件
### 1.每日模块的间距不对。
·间距应为8
<img width="1142" alt="截屏2022-09-22 11 00 15" src="https://user-images.githubusercontent.com/103838357/191648743-aa7eb67e-6e1b-4a0c-ad68-918f3b4f1fe2.png">
### 2.日历头部时间选择组件间距不对。
·上下间距应为32
<img width="1181" alt="截屏2022-09-22 11 15 22" src="https://user-images.githubusercontent.com/103838357/191650541-43893c7b-75c0-467b-ac0c-1726e0e24ded.png">
### 3.选中日期的颜色不对。
·颜色样式为：--td-text-color-primary
<img width="1227" alt="截屏2022-09-22 11 18 45" src="https://user-images.githubusercontent.com/103838357/191650900-652c8f5d-60ce-4efa-b637-10808ca622a0.png">
### 4.日历卡片模式，时间筛选的对齐方式不对。
·时间下拉菜单与卡片左对齐，年/月切换开关与卡片右对齐。
<img width="686" alt="截屏2022-09-22 11 22 26" src="https://user-images.githubusercontent.com/103838357/191651369-b420d849-64e6-4477-a05e-652763dbc970.png">
### 5.日历卡片模式，日期active态、hover态样式不对。
·选中态：大小-24×24，圆角样式--td-radius-default，颜色样式--td-brand-color-light
·悬浮态：大小-24×24，圆角样式--td-radius-default，颜色样式--td-bg-color-secondarycontainer-hover
<img width="839" alt="截屏2022-09-22 11 31 45" src="https://user-images.githubusercontent.com/103838357/191652324-c81e3cba-0a97-4749-9e35-a67223e14720.png">
### 6.日期的文字样式不对
·文字样式为： --td-font-size-title-small

### 1.展示样式没有对齐
·需要纵向居中对齐
<img width="650" alt="截屏2022-09-22 11 34 13" src="https://user-images.githubusercontent.com/103838357/191652695-7099ddc4-85eb-41dd-b05f-636986c5a445.png">

**Comment by PsTiu** [comment]
对应PR：https://github.com/Tencent/tdesign-common/pull/914

**Comment by PsTiu** [comment]
已处理：
![image](https://user-images.githubusercontent.com/880720/196880883-281c5021-b173-40ec-8e10-52b9d52926e8.png)
![image](https://user-images.githubusercontent.com/880720/196881211-1e67349f-18a8-4263-ae62-445f4f7149fc.png)
![image](https://user-images.githubusercontent.com/880720/196881273-f849b572-7ccd-488c-a181-bc44de83d18c.png)

**Comment by eugenewoody** [comment]
版本：react 0.42.5
存在问题：日历卡片模式，时间筛选的对齐方式不对。
修改建议：时间下拉菜单与卡片左对齐，年/月切换开关与卡片右对齐。
<img width="686" alt="191651369-b420d849-64e6-4477-a05e-652763dbc970" src="https://user-images.githubusercontent.com/103838357/199690234-ffdc7484-2155-49ed-ad8a-765059e26efe.png">
