### ISSUE TITLE
[Comment] 样式问题合集

### ISSUE THREAD

**Issue by eugenewoody** [Tencent/tdesign#245]
### tdesign 版本

Vue2 0.47.0｜Vue3 0_21_0｜React 0.41.1

### 1.用户名文字样式不对
·文字样式应为：--td-font-size-title-medium
### 2.头像与评论内容的间距不对
·间距为24
<img width="797" alt="截屏2022-09-22 14 38 14" src="https://user-images.githubusercontent.com/103838357/191675755-30c8dcae-23ed-4c4d-8182-b4c0d6b446e3.png">
### 3.操作按钮文字的大小不对。
·大小应为：--td-font-size-body-small
<img width="909" alt="截屏2022-09-22 14 42 28" src="https://user-images.githubusercontent.com/103838357/191676449-509d5894-f28f-44bf-91b4-d12b245024ed.png">
### 4.操作区按钮的间距不对。
·间距为8
<img width="1774" alt="截屏2022-09-22 14 47 09" src="https://user-images.githubusercontent.com/103838357/191677284-69dbbe8d-52e9-4b7d-ad4f-a0035ebba0b4.png">
### 5.操作区按钮的位置不对。
·操作区按钮位置应统一右对齐
<img width="857" alt="截屏2022-09-22 14 55 04" src="https://user-images.githubusercontent.com/103838357/191678694-5630e458-e7e4-4f5e-b9c6-79ecab6e3961.png">
### 6.回复文本框和回复按钮，间距不对。
·间距应为8
<img width="1028" alt="截屏2022-09-22 14 55 47" src="https://user-images.githubusercontent.com/103838357/191679063-28004b4a-888b-41a9-b6cf-68143b6f10fe.png">
### 7.列表评论，评论之间无分割线。
·应补充分割线
<img width="945" alt="截屏2022-09-22 14 58 18" src="https://user-images.githubusercontent.com/103838357/191679414-5d1daf8c-1d7b-4241-b055-c77f2601aad3.png">

**Comment by xiaosansiji** [comment]
demo 头像统一替换为 https://tdesign.gtimg.com/site/avatar.jpg，与 Vue2 实现保持一致：https://tdesign.tencent.com/vue/components/comment

**Comment by zhangpaopao0609** [comment]
5. 组件不做修改，修改 demo

**Comment by eugenewoody** [comment]
1.版本：vue2 0.49.2
   存在问题：操作区按钮位置应统一右对齐（上述问题5）。
   修改建议：操作区按钮位置应统一右对齐
<img width="845" alt="截屏2022-11-03 下午4 18 37" src="https://user-images.githubusercontent.com/103838357/199675235-108462d7-342c-4e75-a5ce-d8141647e080.png">
