### ISSUE TITLE
[Image] 样式问题合集

### ISSUE THREAD

**Issue by eugenewoody** [Tencent/tdesign#246]
### tdesign 版本

Vue2 0.47.0｜Vue3 0_21_0｜React 0.41.1

### 1.标签字号不对。
·应为--td-font-size-body-small
<img width="350" alt="截屏2022-09-27 16 38 07" src="https://user-images.githubusercontent.com/103838357/192477135-772fcddf-de09-450b-8a75-4714fe3c2344.png">
### 2.默认【加载失败】样式不对。
·需补充icon
<img width="604" alt="截屏2022-09-22 15 55 34" src="https://user-images.githubusercontent.com/103838357/191690511-c4a0cf4c-26c8-4413-bf28-e27d45bd8bad.png">
### 3.遮罩样式不对
·遮罩样式应为：--td-mask-active
### 4.图片列表法中的图片缺少圆角。
·应为：--td-radius-medium
<img width="951" alt="截屏2022-09-22 15 57 33" src="https://user-images.githubusercontent.com/103838357/191690977-a6014aa2-9514-4aeb-9849-1096baefe07a.png">
### 5.加载失败icon大小不对
应为:32×32
### 1.未看到懒加载效果
·建议增加懒加载时长
<img width="642" alt="截屏2022-09-22 15 59 53" src="https://user-images.githubusercontent.com/103838357/191691166-dd319e06-a8f4-4aac-9ccd-5cbc4074f032.png">

### 参考官网一条条修改对照看就好

# IssueShoot
- 预估时长: 1
- 期望完成时间: 2022-10-27
- 开发难度: 低
- 参与人数: 1
- 验收标准: 实现相关接口，提MR并通过验收

**Comment by xiaosansiji** [comment]
组件问题2: 需要使用 `image-error` 图标，已在官方 Icon 库中：
![image](https://user-images.githubusercontent.com/7600149/195010297-2876b54d-71f2-44e9-8b8d-df9de6f6a22a.png)

**Comment by Wen1kang** [comment]
#2092
