### ISSUE TITLE
[list] 样式问题合集

### ISSUE THREAD

**Issue by eugenewoody** [Tencent/tdesign#247]
### tdesign 版本

Vue2 0.47.0｜Vue3 0_21_0｜React 0.41.1

### 1.操作文字按钮颜色样式不对
·应为--td-brand-color
<img width="1065" alt="截屏2022-09-27 16 54 26" src="https://user-images.githubusercontent.com/103838357/192481104-4873fb22-46a3-4bb2-b428-4bf19c7af32a.png">
### 2.列表标题的文字样式不对
·应为--td-font-size-title-medium
<img width="591" alt="截屏2022-09-27 16 55 45" src="https://user-images.githubusercontent.com/103838357/192481374-0bceb4cb-cee9-4038-bba6-ab9961988569.png">
### 3.小/大尺寸的列表间距不对
·左右间距应为24
<img width="709" alt="截屏2022-09-27 16 58 21" src="https://user-images.githubusercontent.com/103838357/192482052-fb7c1479-baf5-4c88-ab0d-99f6021f9cb5.png">
### 4.基础图文列表间距不对
·应为左右24，上下12
<img width="720" alt="截屏2022-09-27 17 03 23" src="https://user-images.githubusercontent.com/103838357/192483589-827a7a24-c7a3-4d1d-ad7b-5ddce18d5261.png">
### _demo_
1.用户头像，建议统一成像素头像
<img width="353" alt="截屏2022-09-27 17 05 52" src="https://user-images.githubusercontent.com/103838357/192484250-ab55123c-c6be-4c43-8a72-d93506b656a3.png">
2.React中，tabs的样式与其他两个技术栈统一
<img width="706" alt="截屏2022-09-27 17 06 56" src="https://user-images.githubusercontent.com/103838357/192484499-417fe5cc-0dde-4871-a4db-c41723cdee27.png">

**Comment by xiaosansiji** [comment]
组件问题1：实际为 demo 实现问题，可以直接使用 Link 组件来改写
![image](https://user-images.githubusercontent.com/7600149/194989925-ad064f3f-27c0-4176-bfe3-83c5336e729a.png)
