### ISSUE TITLE
[Tooltip] 样式问题合集

### ISSUE THREAD

**Issue by eugenewoody** [Tencent/tdesign#250]
### tdesign 版本

Vue2 0.47.0｜Vue3 0_21_0｜React 0.41.1

### 1.Tooltip新增了描边。
·tooltip无描边样式
<img width="324" alt="截屏2022-09-23 16 47 50" src="https://user-images.githubusercontent.com/103838357/191924629-4e7ca9e0-cbdf-4777-abbe-a585f8f88516.png">

**Comment by xiaosansiji** [comment]
预估时常| 期望完成时间 | 验收标准 |
--|--|--
1.0人天 | 2022/10/29 | PR 合入 develop |
