### ISSUE TITLE
[Popconfirm] 样式问题合集

### ISSUE THREAD

**Issue by eugenewoody** [Tencent/tdesign#251]
### tdesign 版本

Vue2 0.47.0｜Vue3 0_21_0｜React 0.41.1

### 1.气泡标题字体样式不对
·应为--td-font-title-small
<img width="388" alt="截屏2022-09-28 上午11 47 52" src="https://user-images.githubusercontent.com/103838357/192683594-c7c04fe3-a432-404b-ae00-dc41edfcda27.png">
### 2.气泡描述文字的颜色不对
·应为--td-text-color-secondary
<img width="396" alt="截屏2022-09-23 20 11 00" src="https://user-images.githubusercontent.com/103838357/191957383-35b27ef7-4b9e-473f-9e80-af56e2741af2.png">

**Comment by iLunZ** [comment]
我来处理

**Comment by eugenewoody** [comment]
版本：vue3 0.49.2 | react 0.42.4
存在问题：描述文字的颜色样式不对。

**Comment by iLunZ** [comment]
> 

vue3和react的修复正在进行中，目前修复了vue2的
