### ISSUE TITLE
[Notification] 样式问题合集

### ISSUE THREAD

**Issue by eugenewoody** [Tencent/tdesign#252]
### tdesign 版本

Vue2 0.47.0｜Vue3 0_21_0｜React 0.41.1

### 1.气泡框无描边。
·需要增加描边，应为0.5的内阴影，颜色样式为：--td-component-border
<img width="466" alt="截屏2022-09-27 19 36 04" src="https://user-images.githubusercontent.com/103838357/192515183-79777f13-338e-4073-b473-c6e7216967d9.png">
### 2.气泡标题样式不对。
·字体是：--td-font-title-medium
<img width="427" alt="截屏2022-09-27 19 39 04" src="https://user-images.githubusercontent.com/103838357/192515745-e945d6f1-298d-41a9-8eff-b42786b15820.png">

**Comment by zhangpaopao0609** [comment]
处理中

**Comment by zhangpaopao0609** [comment]
1. 已修改
2. 无需需改

**Comment by eugenewoody** [comment]
版本：Vue2 0.49.2｜Vue3 0.24.5
存在问题：按钮hover态的圆角不对
修改建议：圆角为--td-radius-default: 3px;
<img width="441" alt="截屏2022-11-03 上午11 08 30" src="https://user-images.githubusercontent.com/103838357/199641359-437b7fb4-d9fd-45cb-a5a4-cbf43453accf.png">
