### ISSUE TITLE
[Alert] 样式问题合集

### ISSUE THREAD

**Issue by eugenewoody** [Tencent/tdesign#253]
### tdesign 版本

Vue2 0.47.0｜Vue3 0_21_0｜React 0.41.1

### 1.警告的上下间距不对
·应为16    
<img width="581" alt="截屏2022-09-24 上午9 47 32" src="https://user-images.githubusercontent.com/103838357/192074988-4106aa35-061b-4de4-b7eb-cfde97091d69.png">      
### 2.icon没有居中
·应居中对齐
<img width="341" alt="截屏2022-09-24 上午8 48 20" src="https://user-images.githubusercontent.com/103838357/192074996-57e79863-520f-4799-8295-48f9e5e7476a.png">
### 3.【展开内容】和内容间距不对
·应为8
<img width="611" alt="截屏2022-09-24 上午9 50 54" src="https://user-images.githubusercontent.com/103838357/192075076-d1d9e684-d518-45bd-93b4-3c04fddbccf8.png">
4.关闭按钮的尺寸大小不对
·应为：16×16
<img width="689" alt="截屏2022-09-27 17 54 40" src="https://user-images.githubusercontent.com/103838357/192496048-800719cc-8bc4-4006-bcfd-f876a88b4b2e.png">
### 1.警告框宽度过窄
·建议根据屏幕宽度自动撑开
<img width="287" alt="截屏2022-09-24 上午9 56 39" src="https://user-images.githubusercontent.com/103838357/192075221-a8285284-84f6-4e85-b30b-cc558b00bb01.png">
### 2.警告缺少关闭按钮
·增加关闭按钮
<img width="586" alt="截屏2022-09-24 上午9 56 55" src="https://user-images.githubusercontent.com/103838357/192075227-fc13610a-c115-4f9e-baf9-53a2c3d4c6d0.png">

**Comment by xiaosansiji** [comment]
demo 2 指 react 技术栈的 demo 实现：https://tdesign.tencent.com/react/components/alert
<img width="591" alt="image" src="https://user-images.githubusercontent.com/7600149/194985273-2591c81b-b517-428c-bd9e-04e5cc38c765.png">

**Comment by aomnisz** [comment]
请问这个点说的是垂直居中还是水平居中？没看出来哪里没居中 =,=
<img width="367" alt="image" src="https://user-images.githubusercontent.com/39907007/197924998-328df746-9bb8-498a-9caa-d42678571c70.png">
