### ISSUE TITLE
[Table] 样式问题合集

### ISSUE THREAD

**Issue by eugenewoody** [Tencent/tdesign#256]
### tdesign 版本

Vue2 0.47.0｜Vue3 0_21_0｜React 0.41.1

### 1.固定表格样式不对。
应为分割线，宽度为4，颜色样式：--td-component-stroke
<img width="431" alt="截屏2022-09-25 下午11 39 15" src="https://user-images.githubusercontent.com/103838357/192152455-172b0872-26b0-4272-a304-ec7680c85c32.png">
### 2.操作文字按钮样式不对
应为：使用link样式，--td-brand-color
<img width="380" alt="截屏2022-09-25 下午11 47 50" src="https://user-images.githubusercontent.com/103838357/192152596-664f63ca-9f2b-43c9-b176-c3c8b2128225.png">
### 3.图标、单选 、多选选区尺寸不对。
·应为：46*46
<img width="502" alt="截屏2022-09-25 下午11 56 16" src="https://user-images.githubusercontent.com/103838357/192152964-2caad751-ceef-401e-82a8-5051f6c1ad99.png">
### 4.表格的左侧间距不对。
·应为24
<img width="596" alt="截屏2022-09-26 上午12 04 37" src="https://user-images.githubusercontent.com/103838357/192153366-e10cd478-7afc-4ac2-a13a-c9ae6ec2b625.png">
### 1.表格样式存在断线
<img width="830" alt="截屏2022-09-26 上午12 19 58" src="https://user-images.githubusercontent.com/103838357/192154127-f36ac685-851b-4f1a-8c2a-23385274b290.png">
### 2.多级表头的筛选条件无间隔
·应保留8的间隔
<img width="1072" alt="截屏2022-09-27 17 46 25" src="https://user-images.githubusercontent.com/103838357/192493766-03323755-b1f9-4df5-8d00-bb80c7524e38.png">
3.多级表头的筛选条件-显示表格边框，暂时先不上。
<img width="1061" alt="截屏2022-09-27 17 50 30" src="https://user-images.githubusercontent.com/103838357/192494696-384fa643-1cbb-4987-8f09-21317a27ebc0.png">

**Comment by xiaosansiji** [comment]
第二条，需要在几个仓库的对应 demo 中替换成用 Link 组件实现 https://tdesign.tencent.com/vue/components/link
![image](https://user-images.githubusercontent.com/7600149/194984280-e64d6cb0-72fd-4cf3-b6ce-4a5544d90268.png)
