### ISSUE TITLE
[Swiper] 样式问题合集

### ISSUE THREAD

**Issue by eugenewoody** [Tencent/tdesign#257]
### tdesign 版本

Vue2 0.47.0｜Vue3 0_21_0｜React 0.41.1

### 1.提示器分式，字号、颜色不对。
·字号样式应为--td-font-size-body-medium，颜色样式为：--td-text-color-secondary
<img width="608" alt="截屏2022-09-26 上午8 57 02" src="https://user-images.githubusercontent.com/103838357/192174579-de7aa20c-1eaf-4d2f-86f5-59fc8c1447ae.png">
### 2.提示器分式，icon箭头大小不对。
·应为16×16
### 3.箭头hover态的样式无圆角。
·应为：--td-radius-default
<img width="699" alt="截屏2022-09-27 17 19 19" src="https://user-images.githubusercontent.com/103838357/192487449-a176aa5a-0a3f-4694-a70d-bedbee0c8cef.png">
4.箭头icon的大小不对。
·箭头的大小为20×20，div为24×24
<img width="617" alt="截屏2022-09-27 17 26 51" src="https://user-images.githubusercontent.com/103838357/192488976-05a0c448-fb1b-4935-823f-8e4261bba29d.png">

**Comment by byq1213** [comment]
已认领
