### ISSUE TITLE
[Transfer] 样式问题合集

### ISSUE THREAD

**Issue by eugenewoody** [Tencent/tdesign#258]
### tdesign 版本

Vue2 0.47.0｜Vue3 0_21_0｜React 0.41.1

### 1.多选框的边距不对。
·间距为8
<img width="558" alt="截屏2022-09-28 上午11 56 25" src="https://user-images.githubusercontent.com/103838357/192684286-ef7622aa-df8b-457e-acd4-0559715cb76c.png">

**Comment by zhangpaopao0609** [comment]
处理中
