### ISSUE TITLE
[Dialog] 样式问题合集

### ISSUE THREAD

**Issue by eugenewoody** [Tencent/tdesign#259]
### tdesign 版本

Vue2 0.47.0｜Vue3 0_21_0｜React 0.41.1

### 1.标题样式不对
·应为--td-font-size-title-medium
<img width="514" alt="截屏2022-09-26 11 36 05" src="https://user-images.githubusercontent.com/103838357/192189045-13ff43da-3daa-41ff-9525-d02d9b7d90aa.png">
### 2.正文的下边距不对
·应为24
<img width="548" alt="截屏2022-09-26 11 37 45" src="https://user-images.githubusercontent.com/103838357/192189216-33a2cf98-c0d3-4fea-ba41-de878342048c.png">
### 3.图标没有居中对齐
·应上下左右居中对齐。
<img width="557" alt="截屏2022-09-26 11 39 43" src="https://user-images.githubusercontent.com/103838357/192189476-23358301-7821-470c-85a8-2a21fed81aa4.png">
### 4.正文的颜色样式不对
·应为--td-text-color-secondary
<img width="524" alt="截屏2022-09-26 11 42 36" src="https://user-images.githubusercontent.com/103838357/192189676-ba82826f-4b9c-499d-ac64-701c5b74fb94.png">
### 1.react中建议不要使用中英文混排
<img width="861" alt="截屏2022-09-27 19 31 31" src="https://user-images.githubusercontent.com/103838357/192514323-405b3154-c125-4e92-bbef-43bb8906a81a.png">

**Comment by Summer-Shen** [comment]
领取 common 和 Vue2 部分

**Comment by Summer-Shen** [comment]
common 这边，

1. 标题样式不对
2. 正文的下边距不对

已经修复并提了 PR https://github.com/Tencent/tdesign-common/pull/967 ；想了解一下 3.图标没有居中对齐 具体指的是？

4. 正文的颜色样式不对 检查了一下，已经是 --td-text-color-secondary 了。

Vue2 这边暂无需要的修改。感谢！
