### ISSUE TITLE
[招募][Sketch] 全局组件/样式/示例/命名优化

### ISSUE THREAD

**Issue by Wen1kang** [Tencent/tdesign#265]
### Sketch 设计资源组件设计

**🔥 长期招募贡献者设计并维护 Sketch 样式和Symbol**

### 全局组件优化（组件/样式/命名）

1. 锚点
2. 面包屑
3. 下拉菜单
4. 列表
5. 评论组件
6. 折叠面板
7. 标签
8. 数字输入框
9. 单选框与多选框
10. 滑块
11. 穿梭框

### 样式优化

1. 头像
2. 警告
3. 气泡确认框

### 示例页

所有示例页面均需要对齐Figma示例展示形式

### 合并组件

需要合并 image/imageView/card/link 四个组件

#

### Tips

- 需要有 Sketch 使用经验的设计同学参与，**高难度**
- 认领任务前联系，可以进群进行前期沟通，使用微信或企业微信扫码加入

<img width="280" alt="Snipaste_2022-08-31_17-58-49" src="https://user-images.githubusercontent.com/89069385/187654607-2695d1db-8327-42bb-a03d-6b40a2affd59.png">

### 激励

- 参与共建的开发者，将可以获得 [TDesign 周边](https://github.com/Tencent/tdesign/wiki/TDesign-%E5%91%A8%E8%BE%B9)（贴纸、鼠标垫、工卡套等）；
- 成为核心贡献者，将会拥有 TDesign 专属头像。

**Comment by burtonx** [comment]
已领取

**Comment by Wen1kang** [comment]
已完成
