### ISSUE TITLE
[文档] 表格的写法存在兼容性问题

### ISSUE THREAD

**Issue by tolking** [Tencent/tdesign#266]
### tdesign 版本

-

### 重现链接

https://github.com/Tencent/tdesign-vue-next/blob/develop/src/image-viewer/image-viewer.md#imageviewer-props

### 重现步骤

使用 Github, VSCode 等工具查看时格式错误

文档`说明`里面的部分内容将可能被渲染到`必传`中

### 期望结果

写法具有更好的兼容性

### 实际结果

Github, VSCode 等 markdown 解析后格式错误

### 框架版本

-

### 浏览器版本

-

### 系统版本

-

### Node版本

-

### 补充说明

> onIndexChange | Function |  | TS 类型：`(index: number, context: { trigger: 'prev' | 'next' }) => void`<br/>预览图片切换时触发，`context.prev` 切换到上一张图片，`context.next` 切换到下一张图片 | N

例如引用内容中的 `(index: number, context: { trigger: 'prev' | 'next' }) => void` 写法将产生错误。其中的 `|` 被解析成分割表格列而不是分割类型，从而产生错误

这里的 `|` 应该使用转译符会更兼容些 `(index: number, context: { trigger: 'prev' \| 'next' }) => void`

所有使用包含 `` | `` 格式的文档都存在这个问题。如 [react](https://github.com/Tencent/tdesign-react/blob/develop/src/image-viewer/image-viewer.md) [vue-next](https://github.com/Tencent/tdesign-vue-next/blob/develop/src/image-viewer/image-viewer.md#imageviewer-props) ...

**Comment by xiaosansiji** [comment]
fixed in https://github.com/TDesignOteam/tdesign-api/pull/50
目前 TDesign 桌面端几个仓库文档已经是修正过的了，例如 https://github.com/Tencent/tdesign-vue-next/blob/develop/src/image-viewer/image-viewer.md#imageviewer-props
