### ISSUE TITLE
TDesign升级新版本为什么从不考虑兼容老版本

### ISSUE THREAD

**Issue by ppya0812** [Tencent/tdesign#279]
### tdesign 版本

0.42.5

### 期望结果

tdesign升级的新版本能兼容老版本

### 实际结果

tdesign每次升级都一堆现网bug，或者增加一堆改造的工作量

### 框架版本

react

**Comment by xiaosansiji** [comment]
目前组件库还处于 0.x 的测试版本，为了保持能够快速迭代新版本当前阶段暂不考虑向前兼容，为了降低 breaking change 带来的影响，存在不兼容更新时会发布 breaking change 版本，并在 changlog 里做特别说明：
https://tdesign.tencent.com/react/changelog#%F0%9F%8C%88-0-42-0-2022-09-20
<img width="911" alt="image" src="https://user-images.githubusercontent.com/7600149/200475234-bd6c2369-51d3-4901-9b31-e29cae747e1e.png">

发布 1.x 版本后会考虑逐步增加兼容手段，比如确定要去除的 API 会暂时保留几个版本，并在开发环境控制台中打印相关警告信息，预告在哪个版本中不再支持
