### ISSUE TITLE
[table] 合并单元格有时候无效

### ISSUE THREAD

**Issue by 2513483494** [Tencent/tdesign#291]
### tdesign 版本

0.43.1

### 重现步骤

<img width="639" alt="截屏2022-12-08 19 23 12" src="https://user-images.githubusercontent.com/48058550/206434569-de78ecee-852a-4e74-9a7c-2bf5590c2698.png">
按照这个方式合并单元格，有时候生效有时候无效。
需求就是同一列名字一样的话就可以合并。

### 期望结果

需求就是同一列名字一样的话就可以合并。

**Comment by 2513483494** [comment]
https://github.com/Tencent/tdesign-react/issues/1632
之前的issue是这个，但是更新版本后这个方法经常没效果

**Comment by chaishi** [comment]
https://github.com/Tencent/tdesign-react/issues
以后尽量在上面的仓库提 issue，提高被发现的可能

**Comment by chaishi** [comment]
提供可复现问题的链接，可以更快速地回应或解决问题
