### ISSUE TITLE
[Table] onDragSort函数里面无法使用state状态值

### ISSUE THREAD

**Issue by 2513483494** [Tencent/tdesign#294]
### tdesign 版本

0.43.1

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-7dm0lc?file=/src/demo.jsx

### 重现步骤

最简单的上面的连接，点击按钮改变值，但是打印出来还是初始值。

### 期望结果

在onDragSort可以正常使用状态值。

**Comment by lich-yoo** [comment]
链接中的示例被修改了，无法看出问题。
可复现的链接可以参考如下：https://codesandbox.io/s/tdesign-react-table-drag-bug-9s9fhl?file=/src/demo.jsx
