### ISSUE TITLE
能否支持国际化 多语言

### ISSUE THREAD

**Issue by wangzhen1990** [Tencent/tdesign#298]
### 这个功能解决了什么问题

适合有多语言时使用

### 你建议的方案是什么

增加多语言

**Comment by chaishi** [comment]
https://tdesign.tencent.com/react/config
https://tdesign.tencent.com/vue/config
https://tdesign.tencent.com/vue-next/config
请参考全局配置页面进行语言配置。由于不知道你用的什么框架，上面都贴了地址
