### ISSUE TITLE
Tdesign 的色彩说明的md文件是在那个仓库维护的呢

### ISSUE THREAD

**Issue by BobCFD** [Tencent/tdesign#300]
https://tdesign.tencent.com/design/color
这个页面的文件是在那个仓库维护呢？想了解一下色彩组件引入到md的展示
![image](https://user-images.githubusercontent.com/10686735/216315908-3d929492-b1cb-42ca-8345-31b3846493aa.png)

**Comment by xiaosansiji** [comment]
参考下这里 https://github.com/TDesignOteam/tdesign-site/blob/main/site/src/pages/design/color.vue

**Comment by uyarn** [comment]
全部文档目前都已迁移到此仓库
