### ISSUE TITLE
[颜色选择器]

### ISSUE THREAD

**Issue by FFEverglow** [Tencent/tdesign#303]
### 这个功能解决了什么问题
有时候有渐变颜色需求的时候,不希望添加多个色段,只希望保持两个或者几个色段.

### 你建议的方案是什么？
建议可以让用户选择选择渐变颜色时色段的数量限制,防止用户点击添加多个色段时造成的问题.

**Comment by uyarn** [comment]
duplicate of https://github.com/Tencent/tdesign-vue/issues/2140
