### ISSUE TITLE
桌面端 StickyTool 侧边栏

### ISSUE THREAD

**Issue by xiaosansiji** [Tencent/tdesign#306]
### 设计稿
https://codesign.qq.com/s/P4VlZMARJdZq6wL
访问密码：S3PY

已实现的技术栈：

- [x] tdesign-vue @ZekunWu https://github.com/Tencent/tdesign-vue/pull/2213
- [x] tdesign-vue-next @ZekunWu https://github.com/Tencent/tdesign-vue-next/pull/2517
- [x] tdesign-react @ZekunWu https://github.com/Tencent/tdesign-react/pull/2065

### 参与贡献

如果你想要认领组件开发，请在本 issue 中评论认领并预估提交 PR 时间，例：

> “我认领这个组件 tdesign-vue 仓库的实现任务，预计 x 日后提交”

请尽量在预期时间内完成，超期后 PMC 同学可能会联系其他同学接手实现。

详细提交过程请参考：[如何贡献](https://tdesign.tencent.com/about/contributing)。

欢迎填写[《贡献者加入意向收集》](https://wj.qq.com/s2/9772260/7cbe/)问卷加入 TDesign 贡献者群，参与过程中遇到的各类问题可以得到实时解答和指引。

**Comment by ZekunWu** [comment]
我认领这个组件 tdesign-vue、tdesign-vue-next、tdesign-react仓库的实现任务，预计 16日后提交
