### ISSUE TITLE
Backtop 返回顶部组件 

### ISSUE THREAD

**Issue by xiaosansiji** [Tencent/tdesign#308]
### 设计稿
【腾讯 CoDesign】三期组件
https://codesign.qq.com/s/5l429llrV89dYDO
访问密码：QE1Z

已实现的技术栈：

- [x] tdesign-vue @uyarn https://github.com/Tencent/tdesign-vue/pull/2368
- [x] tdesign-vue-next @shinyina https://github.com/Tencent/tdesign-vue-next/pull/2665
- [x] tdesign-react @meiqi502 https://github.com/Tencent/tdesign-react/pull/2037

### 参与贡献

如果你想要认领组件开发，请在本 issue 中评论认领并预估提交 PR 时间，例：

> “我认领这个组件 tdesign-vue 仓库的实现任务，预计 x 日后提交”

请尽量在预期时间内完成，超期后 PMC 同学可能会联系其他同学接手实现。

详细提交过程请参考：[如何贡献](https://tdesign.tencent.com/about/contributing)。

欢迎填写[《贡献者加入意向收集》](https://wj.qq.com/s2/9772260/7cbe/)问卷加入 TDesign 贡献者群，参与过程中遇到的各类问题可以得到实时解答和指引。

**Comment by tangzixuan** [comment]
我想认领此组件的开发，预计在2023-02-27日前完成

**Comment by tangzixuan** [comment]
请问https://github.com/Tencent/tdesign-mobile-react，mobile组件库需求补这个组件嘛

**Comment by tangzixuan** [comment]
@xiaosansiji  请教一个问题，我在开发这个组件时遇到一些问题，我基于tdesign-react来fork了一下，当我需要同时改到tdesign-react和tdesign-common的时候怎么提交呢，一定要分成2个pr来最终提交嘛

**Comment by xiaosansiji** [comment]
> 请问[https://github.com/Tencent/tdesign-mobile-react，mobile组件库需求补这个组件嘛](https://github.com/Tencent/tdesign-mobile-react%EF%BC%8Cmobile%E7%BB%84%E4%BB%B6%E5%BA%93%E9%9C%80%E6%B1%82%E8%A1%A5%E8%BF%99%E4%B8%AA%E7%BB%84%E4%BB%B6%E5%98%9B)
小程序里已经实现了这个组件了，同为移动端的 mobile-react 也需要实现它，但遵循的是移动端的交互和设计稿，跟当前这个 issue 里桌面的会有点不一样，你可以参照移动端的来实现

**Comment by tangzixuan** [comment]
好的，我在tdesign-mobile-react看到这个组件了，只是有些疑惑通过这个通过gitsubmobile的方式来复用其它仓库，当我同时需要改动到2个仓库的时候，我开发的时候怎么调试呢，上面我已经拉了2个基础的mr了，请问下你们开发当2个仓库需要同时改的时候是怎么弄的呀

**Comment by xiaosansiji** [comment]
需要分别 fork 两个仓库，提交两个 PR，先提交 submodule 仓库的，再提交 tdesign-mobile-react 仓库的，类似下面这两个：
common: https://github.com/Tencent/tdesign-common/pull/1153
common 的 PR 合并后，发起主仓库的 PR 把 common 的 commit ID 更新上去：
https://github.com/Tencent/tdesign-vue/pull/2176
<img width="499" alt="image" src="https://user-images.githubusercontent.com/7600149/220602867-2158715c-7da7-4d4e-ab6d-1080f93236c6.png">

<img width="947" alt="image" src="https://user-images.githubusercontent.com/7600149/220602970-93c69889-2cbe-4976-8788-fd7bf7990a5a.png">

**Comment by tangzixuan** [comment]
明白了，谢谢😊

**Comment by tangzixuan** [comment]
- https://github.com/Tencent/tdesign-react/pull/2022
- https://github.com/Tencent/tdesign-common/pull/1154
- 辛苦帮忙review一下

**Comment by RADWIMPS426** [comment]
### **以下调整，圆形组件同理**
### **1.backtop三个主题的icon，距离顶部这里有2px**
<img width="498" alt="image" src="https://user-images.githubusercontent.com/124988288/224220846-101b9cde-911d-4af4-b893-1065fbd385aa.png">

### **2.主题色与黑色的backtop，icon和text的token使用错误，应为--td-text-color-anti**
<img width="974" alt="image" src="https://user-images.githubusercontent.com/124988288/224220988-d87e3f39-4251-4b47-abde-f539f9d2d56c.png">

### **3.黑色的backtop使用颜色值不需引用token，使用rgba(0, 0, 0, 0.9)，hover态为rgba(0, 0, 0, 0.6)**
<img width="676" alt="image" src="https://user-images.githubusercontent.com/124988288/224221160-3d53e2c9-6872-441c-a954-48b77c5512ec.png">

### **4.组件间隔的展示，横向请调整为24px，纵向为32px，其它展示同理**
<img width="376" alt="image" src="https://user-images.githubusercontent.com/124988288/224221263-4e57561e-69a0-47e0-b45e-676279b448fe.png">

**Comment by shinyina** [comment]
hi,请问还打算做vue和vue-next的部分吗，我想认领vue-next的实现

**Comment by shinyina** [comment]
你好，vue-next没有生成props.ts和type.ts

**Comment by uyarn** [comment]
> 你好，vue-next没有生成props.ts和type.ts

@shinyina  props和type 需要用API工具生成  https://github.com/Tdesignoteam/tdesign-api

**Comment by xiaosansiji** [comment]
感谢各位，桌面端 Backtop 返回顶部组件三个主要技术栈已经全部发布上线
