### ISSUE TITLE
NoticeBar 公告栏 可滚动公告栏选为 horizontal 滚动时会出现Uncaught (in promise) null(env: Windows,mp,1.06.2303060; lib: 2.30.3)，vertical 滚动就没问题

### ISSUE THREAD

**Issue by huangkengrun** [Tencent/tdesign#318]
### tdesign 版本

1.0.3

### 重现步骤

引入公告栏组件后，可滚动公告栏选为 horizontal 滚动时控制台会出现Uncaught (in promise) null(env: Windows,mp,1.06.2303060; lib: 2.30.3)，vertical 滚动就不会出现

### 框架版本

miniprogram 2.30.3

### Node版本

v18.12.1

**Comment by xiaosansiji** [comment]
需要补充组件库信息（技术栈等），提供必要的截图或在线 demo 链接
