### ISSUE TITLE
Vue Next for Mobile 可以在 UniApp中使用吗？

### ISSUE THREAD

**Issue by daniel031699** [Tencent/tdesign#329]
### tdesign 版本

0.18.0

### 重现步骤

根据文档提示引入 ，没有样式

### 期望结果

可以在uniapp中使用 Vue Next 

### 实际结果

可以在uniapp中使用 Vue Next 

### Node版本

17

### 补充说明

我们使用 uniapp开发并使用 Vue Next 开发 一个小程序。

**Comment by ngyyuusora** [comment]
uniapp小程序不可用
