### ISSUE TITLE
【TDesign】是不打算做Angular版本了吗

### ISSUE THREAD

**Issue by ZebraCY** [Tencent/tdesign#331]
### 这个功能解决了什么问题

扩大tdesign技术栈覆盖范围

### 你建议的方案是什么

看官网文档已经没了ng版本，看仓库文档又有，阿里做的ng-zorro有点不够用了

**Comment by xiaosansiji** [comment]
还在做，仓库在内部维护中，但腾讯内部使用 ng 的团队越来越少了，组件库实现质量和迭代速度都不如预期，打算近期把仓库迁移到 GitHub 上来，让外部同学也可以参与维护。感兴趣的话后面也可以参与哈～
