### ISSUE TITLE
官网挂了 

### ISSUE THREAD

**Issue by vaynevayne** [Tencent/tdesign#333]
### tdesign 版本

latest

### 重现步骤

https://tdesign.tencent.com/

<img width="948" alt="image" src="https://github.com/Tencent/tdesign/assets/124666577/d336e0f0-4b02-4f19-a96a-6a67be8130dc">

**Comment by xiaosansiji** [comment]
排查中，某些 referer 貌似被 ban 了。。

**Comment by overtrue** [comment]
@vaynevayne 感谢反馈，请问可以稳定复现吗？还是偶发，如果方便麻烦把报错页的 RequestId 和 TraceId 复制一下方便我们排查，感谢！

**Comment by vaynevayne** [comment]
下次遇到发给你

**Comment by overtrue** [comment]
> 话说截图上不是有吗

嗯嗯，感谢🙏
