### ISSUE TITLE
TDesign 的官网对百度的支持目前不太友好

### ISSUE THREAD

**Issue by xy60cn** [Tencent/tdesign#35]
**Is your feature request related to a problem? Please describe.**
TDesign 的官网对百度的支持目前不太友好

**Describe the solution you'd like**
期望通过ssr或类似的技术提高对搜索引擎的支持
可以一期先完成首页的支持
二期完成全站的支持

另外，
1,
![1641989257(1)](https://user-images.githubusercontent.com/74610452/149137518-28180357-0321-4cdd-a500-d8f8d2ead131.png)
顶部左上的LOGO ，增加alt 标签，内容：TDesign ，点击可链接导首页

2, 
为产品体验设计的各个环节提供解决方案，做好连接的角色，赋能更多的行业领域，助力提升产品体验，有效提升设计研发效能。
改为：
TDesign 为产品体验设计的各个环节提供解决方案，做好连接的角色，赋能更多的行业领域，助力提升产品体验，有效提升设计研发效能。

3，
![1644569417(1)](https://user-images.githubusercontent.com/74610452/153562063-af548780-51d2-4ec6-acf9-65cf9d01151b.png)
这里的头像链接，增加 nofollow 标签
`<a href="XXX" target="_blank" rel="nofollow">XXX</a>`

**Comment by HQ-Lin** [comment]
> **Is your feature request related to a problem? Please describe.** TDesign 的官网对百度的支持目前不太友好
> 
> **Describe the solution you'd like** 期望通过ssr或类似的技术提高对搜索引擎的支持 可以一期先完成首页的支持 二期完成全站的支持
> 
> 另外， 1, ![1641989257(1)](https://user-images.githubusercontent.com/74610452/149137518-28180357-0321-4cdd-a500-d8f8d2ead131.png) 顶部左上的LOGO ，增加alt 标签，内容：TDesign ，点击可链接导首页
> 
> 2, 为产品体验设计的各个环节提供解决方案，做好连接的角色，赋能更多的行业领域，助力提升产品体验，有效提升设计研发效能。 改为： TDesign 为产品体验设计的各个环节提供解决方案，做好连接的角色，赋能更多的行业领域，助力提升产品体验，有效提升设计研发效能。
> 
> 3， ![1644569417(1)](https://user-images.githubusercontent.com/74610452/153562063-af548780-51d2-4ec6-acf9-65cf9d01151b.png) 这里的头像链接，增加 nofollow 标签 `<a href="XXX" target="_blank" rel="nofollow">XXX</a>`

1. 鼠标移入提示已处理
![image](https://user-images.githubusercontent.com/24469546/154001950-f5ab1dfa-1066-4885-ab4e-83b7cfd74b0f.png)
2.文案已调整
3.已添加 nofollow 属性
