### ISSUE TITLE
[checkbox] 按钮形式多选框

### ISSUE THREAD

**Issue by liweijie0812** [Tencent/tdesign#370]
### 这个功能解决了什么问题

单选的按钮样式有了
<img width="831" alt="image" src="https://github.com/Tencent/tdesign/assets/10710889/f0110c33-179e-4f5b-a0b7-18cf4c2fef2e">

缺多选的按钮样式

### 你建议的方案是什么

<img width="835" alt="image" src="https://github.com/Tencent/tdesign/assets/10710889/08d11bf8-4229-4b15-8d28-58c21611bb73">

**Comment by uyarn** [comment]
标签组中实现 https://tdesign.tencent.com/vue-next/components/tag#%E5%8F%AF%E9%80%89%E6%8B%A9%E6%A0%87%E7%AD%BE%E7%BB%84
