### ISSUE TITLE
[文档错误] 「设计」版块文档内容错误

### ISSUE THREAD

**Issue by tawangwuhen** [Tencent/tdesign#373]
### tdesign 版本

文档文案错误

### 重现链接

https://tdesign.tencent.com/design/offices-task#b-%E6%89%B9%E9%87%8F%E6%96%87%E4%BB%B6%E5%AF%BC%E5%85%A5

### 重现步骤

![image](https://github.com/Tencent/tdesign/assets/23145193/5689e647-39e9-470c-84ef-a362472eaf76)

### 期望结果

![image](https://github.com/Tencent/tdesign/assets/23145193/c6074408-3fc6-44e1-ad88-db046e6e91ed)

**Comment by xiaosansiji** [comment]
已经修复了
