### ISSUE TITLE
Mentions 组件几种实现方案

### ISSUE THREAD

**Issue by ocweai** [Tencent/tdesign#390]
## 组件名称中英文
提及
Mentions
### 实现方案
子元素额外逻辑？click、delete、color、backgound-color...
- textarea 优点简单易懂成本低，缺点交互简单数据模型为字符串格式
- contenteditable 优点支持复杂交互，缺点光标定位、排版和渲染引擎较复杂
- canvas 参考 google doc

### 交互稿

交互稿：

### 设计稿

设计稿：

已实现的技术栈：

- [ ] tdesign-vue
- [ ] tdesign-vue-next
- [ ] tdesign-react

### 参与贡献

如果你想要认领组件开发，请在本 issue 中评论认领并预估提交 PR 时间，例：

> “我认领这个组件 tdesign-vue 仓库的实现任务，预计 x 日后提交”

请尽量在预期时间内完成，超期后 PMC 同学可能会联系其他同学接手实现。

详细提交过程请参考：[如何贡献](https://tdesign.tencent.com/about/contributing)。

欢迎填写[《贡献者加入意向收集》](https://wj.qq.com/s2/9772260/7cbe/)问卷加入 TDesign 贡献者群，参与过程中遇到的各类问题可以得到实时解答和指引。

**Comment by badspider7** [comment]
你好，请问有具体地址吗
