### ISSUE TITLE
希望添加一个功能，可以满足用户自己对原始组件库添加新功能等等

### ISSUE THREAD

**Issue by itfxl** [Tencent/tdesign#417]
希望出一个接口或者功能，可以使得用户自己对本组件添加新功能、属性等，同时不需要用户自己去注册这个组件，相对对本组件进行扩展，抛弃以前的做法，对组件二次封装，然后重新引入使用

**Comment by uyarn** [comment]
你说的应该pnpm patch https://pnpm.io/cli/patch 是可以做到的吧
