### ISSUE TITLE
[菜单] 报错TypeError: Cannot read properties of undefined (reading 'path') 点击侧面菜单后 url已经发生变化，但是页面不跳转

### ISSUE THREAD

**Issue by FANGLANYAN** [Tencent/tdesign#457]
### tdesign 版本

 "tdesign-vue-next": "^0.26.2",

### 重现步骤

![8d5cd928c4f77c5fde6b39be94d03a6a](https://github.com/Tencent/tdesign/assets/37475285/a12179b2-e712-4808-8666-812d327e04ec)

### 框架版本

 "vue": "^3.2.31",

### 浏览器版本

chrome 122.0.6261.57（正式版本） (arm64)

### 系统版本

MacOS(14.2.1)

### Node版本

21.6.0

### 补充说明

才根据官网npm的引入方式初始化项目 然后正常启动 电机侧边二级菜单、无法跳转

**Comment by uyarn** [comment]
vue3.4发布之后的问题 "vue": "^3.2.31" 会安装到3.4 改成~3.2.31先保证不会装到3.4

**Comment by Misayahr** [comment]
问题还是存在啊

**Comment by Misayahr** [comment]
近期是 哪一期啊
