### ISSUE TITLE
[组件名称] 描述问题的标题

### ISSUE THREAD

**Issue by WhiteCata** [Tencent/tdesign#465]
### tdesign 版本

stable

### 重现链接

https://tdesign.tencent.com/miniprogram/overview

### 重现步骤

https://tdesign.tencent.com/miniprogram/overview， 

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0

### 期望结果

正常显示就好

### 实际结果

![tttttt](https://github.com/Tencent/tdesign/assets/27550276/085a5e7b-7df7-4e4c-9325-9ad6d6ddede5)
预览黑屏

### 框架版本

all

### 浏览器版本

firefox

### 系统版本

win64

```[tasklist]
### Tasks
```

**Comment by WhiteCata** [comment]
https://tdesign.tencent.com/miniprogram/overview,还有小程序哦

**Comment by WhiteCata** [comment]
应该是在火狐浏览器上的所有版本和平台

**Comment by uyarn** [comment]
<img width="1435" alt="image" src="https://github.com/Tencent/tdesign/assets/26377630/3dae547e-e05f-4e9d-849f-262231ac1384">
mac可以正常展示 是windows的原因？

**Comment by yanhao98** [comment]
"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0" 

<img width="1650" alt="image" src="https://github.com/Tencent/tdesign/assets/37316281/189b39ac-5f85-4616-913f-07f9dbb4b495">
