### ISSUE TITLE
咨询下 flutter 桌面端有计划吗？

### ISSUE THREAD

**Issue by wayddmldbzz** [Tencent/tdesign#484]
### 这个功能解决了什么问题

flutter 的桌面端组件太少了，好用的更少移动端出来桌面端有计划吗？

### 你建议的方案是什么

只是咨询

**Comment by uyarn** [comment]
按计划顺利会做桌面端的适配 但是现在还在做好移动端的质量阶段 可以到flutter参考 https://github.com/Tencent/tdesign-flutter
