### ISSUE TITLE
如何替换字体资源路径

### ISSUE THREAD

**Issue by myforest0** [Tencent/tdesign#488]
### tdesign 版本

0.13.0

### 重现步骤

[渲染层网络层错误] Failed to load font https://tdesign.gtimg.com/icon/0.1.4/fonts/t.woff

**Comment by uyarn** [comment]
ignore it 
refer to
![image](https://github.com/Tencent/tdesign/assets/26377630/12c575eb-6143-4473-9646-65dac430177f)
