### ISSUE TITLE
[Tabs] 支持通过滚轮或者触摸板操作

### ISSUE THREAD

**Issue by oljc** [Tencent/tdesign#498]
### 这个功能解决了什么问题

现在的 Tabs 组件只能通过点击两边的操作区进行滚动控制，无法通过滚轮和触摸板进行滚动不是很方便。
1. 支持通过滚轮或者触摸板操作
2. 支持控制被选中 tab 的滚动位置 如：`'auto' | 'start' | 'center' | 'end'`
例：[Ant Design](https://ant.design/components/tabs-cn)、[Arco Design](https://arco.design/react/components/tabs#%E6%BB%9A%E5%8A%A8)

### 你建议的方案是什么

支持通过滚轮或者触摸板操作

**Comment by uyarn** [comment]
Preview看了下 第一个功能很赞👍 第二个是什么场景需要使用的没太理解

**Comment by oljc** [comment]
> Preview看了下 第一个功能很赞👍 第二个是什么场景需要使用的没太理解

类似标签这种 Tab 较多的时候，将滚动位置设置为居中那么每次选中标签都可以看到前后附近的标签无需切换或滚动。

https://github.com/Tencent/tdesign/assets/48879481/f4e24e7c-d1c3-49b5-9c02-9da36b155b83
