### ISSUE TITLE
希望增加二维码、条形码组件库

### ISSUE THREAD

**Issue by mustars** [Tencent/tdesign#507]
### 这个功能解决了什么问题

在当前数字化时代，二维码和条形码已成为连接物理世界与数字世界的桥梁，广泛应用于信息分享、产品追踪、票证验证、移动支付等多个领域。然而使用TDesign构建应用时，缺少直接支持生成二维码与条形码的官方组件，这导致开发人员需要额外集成第三方库或自建解决方案，增加了项目复杂度、维护成本，并可能因引入外部依赖而影响应用的整体稳定性和一致性。

### 你建议的方案是什么

提升开发效率；保证设计一致性；简化维护工作；增强功能全面性；

**Comment by uyarn** [comment]
二维码会增加的 
条形码没有这个计划 
其他组件 关注 https://github.com/Tencent/tdesign/issues/220 的进展即可
