### ISSUE TITLE
谷歌、edge浏览器官网显示异常

### ISSUE THREAD

**Issue by tsebim** [Tencent/tdesign#517]
### tdesign 版本

1.0 LTS

### 重现链接

https://tdesign.tencent.com/

### 重现步骤

[官网文档页面使用谷歌浏览器和edge访问页面显示异常
![PixPin_2024-08-02_20-02-28](https://github.com/user-attachments/assets/96daba93-009b-4492-81a6-60c68ee1fe65)

### 期望结果

修复

### 浏览器版本

127.0.6533.89

**Comment by uyarn** [comment]
麻烦打开无痕看下是否正常

**Comment by tsebim** [comment]
tsebim收到来信

**Comment by uyarn** [comment]
这个现象一般都是插件引起的，长时间没有回复关闭issue了，如果还有其他问题麻烦重新打开或者另提issue。

**Comment by tsebim** [comment]
tsebim收到来信
