### ISSUE TITLE
[AI代码生成器] 根据图片或解析url或html直接生成tdesign业务源码

### ISSUE THREAD

**Issue by mansai** [Tencent/tdesign#528]
### 这个功能解决了什么问题

例如这个图片
![image](https://github.com/user-attachments/assets/cbb22f12-d57d-47ee-8b58-d3786745b89a)

### 你建议的方案是什么

根据产品经理的原型图，直接生成对应的业务源代码

**Comment by uyarn** [comment]
这是其他D2C的产品会提供的功能
