### ISSUE TITLE
[github] 使用 issue-helper 新建 功能失效

### ISSUE THREAD

**Issue by kajweb** [Tencent/tdesign#543]
![image](https://github.com/user-attachments/assets/f544e78d-cd01-4e7c-9138-48d1ffadf3d6)

[https://tencent.github.io/tdesign/issue-helper/?lang=zh-CN&repo=Tencent/tdesign-react](https://tencent.github.io/tdesign/issue-helper/?lang=zh-CN&repo=Tencent/tdesign-react)无法打开

**Comment by uyarn** [comment]
已恢复
