### ISSUE TITLE
treeselect 组件vue版本父节点禁用，子节点怎么可以不禁用？

### ISSUE THREAD

**Issue by HowLoveYou** [Tencent/tdesign#572]
### tdesign 版本

1.10.5

### 框架版本

vue2

### 补充说明

项目开发使用的0.46.5版本，现在已经升级到1.10.5，希望支持

**Comment by uyarn** [comment]
set tree-props checkStrictly as true
<img width="862" alt="image" src="https://github.com/user-attachments/assets/00b6dbb0-5318-4b4d-8742-a5d25b472fd8">
