### ISSUE TITLE
Can it support accessibility？

### ISSUE THREAD

**Issue by gzzhengbingyi** [Tencent/tdesign#6]
Large companies like Tencent, whether in their business or social influence, should consider accessibility.

**Comment by xiaosansiji** [comment]
https://github.com/Tencent/tdesign/projects/1

**Comment by huangzhongzhong** [comment]
这个进度看板主要是从开发侧的视角看待的，能否提供一个设计侧视角的看板呢@94dreamer

**Comment by 94dreamer** [comment]
@pattybaby110  如上
