### ISSUE TITLE
这里的图标是不是用的不够统一？一会是警告图标 一会是信息图标

### ISSUE THREAD

**Issue by tdesign-helper** [Tencent/tdesign#66]
sketch文件：这里的图标是不是用的不够统一？一会是警告图标 一会是信息图标
![MTY4ODg1NDM0OTI1MTYyNg_437888_bct-3Kr-4X9Vob0t_1642563059](https://user-images.githubusercontent.com/96863479/150507915-5507ac25-0819-4af0-8bf5-8cf2af179fce.jpg)

**Comment by pattybaby110** [comment]
已经解决了，新版本已经更新到官网
