### ISSUE TITLE
[提议] 提升代码质量和专业性

### ISSUE THREAD

**Issue by Yilun-Sun** [Tencent/tdesign#79]
人人都应该安装的 VSCODE 插件：
[code-spell-checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) 它不香吗
作为一个开源 repo，要尽量避免出现低级的 typo 哇。

后续：
是否能让 VSCODE 打开这个 repo 时，可以自动安装插件？

**Comment by 94dreamer** [comment]
背收录到 #21
