### ISSUE TITLE
What is the most difference, compare with ant-design?

### ISSUE THREAD

**Issue by keepsilentw** [Tencent/tdesign#8]

**Comment by iheshime** [comment]
It's from Tencent, not Alibaba. 😄 
Just kidding.

**Comment by chaishi** [comment]
UI

**Comment by 94dreamer** [comment]
@keepsilentw 你想了解的是哪方面的不同 
What are the differences you want to understand

**Comment by keepsilentw** [comment]
> 

I'm a developer, I want to know the strengths of tdesign, when I use it.

**Comment by 94dreamer** [comment]
@keepsilentw readme 和 [官网](https://tdesign.tencent.com/about/introduce) 阐述了我们的特性。

长期来看，我们的产品特点是 多端覆盖/多技术栈实现/设计体系完整统一/设计资源丰富。

这可能意味着这种场景下：多个前端应用，并且有着不同的技术栈，不同的端，并且想保持一致的设计，一致的组件API
我们会更有产品定位的优势。

当然，业界少数知名的组件库也可能有多技术栈和不同端的实现，不过大多数不是官方首推。
另外，我们指的 多端覆盖/多技术栈支持 和 跨端跨框架解决方案 是不同维度的。
